### ISSUE TITLE
Undo a move

### ISSUE THREAD

**Issue by asifmallik** [jhlywa/chess.js#103]
Is there a way to undo a move that was made?

**Comment by crapomat** [comment]
There is .undo() 
https://github.com/jhlywa/chess.js/blob/master/README.md#undo
I believe the example is incorrect, it shows same FEN for game after first move and after .undo(). Last FEN in example should show start position.

**Comment by asifmallik** [comment]
Thank you, can't believe I missed that

**Comment by jhlywa** [comment]
@crapomat Thanks for the heads up about the FEN typo in `undo`
