### ISSUE TITLE
Can i tweak the api to show legal moves for one piece only ?

### ISSUE THREAD

**Issue by shaktisd** [jhlywa/chess.js#108]
I want to create a small application to teach kids how each piece moves, for that 
I want to use your api to show legal moves for 1 piece on the board. Like for example. I want to place only one rook or two rooks on the board and then when they click on the rook it will show them the possible squares where they can move. I know this sounds a little odd but it will be of great help if you can tell if I can do it with the current api.

**Comment by jhlywa** [comment]
You can always use `moves({square: 'e2'})` if you are using legal positions (e.g. both sides have a king).  You might be able to generate moves for invalid positions by trying something like:

```
// this is all untested
> chess.put({type: chess.ROOK, color: chess.WHITE }, 'a1');
> chess.moves({legal: false, square 'a1'})
```

Turning off legality checking disables check checking, so if you have a position with say a knight pinned to a king, you will get invalid moves.
