### ISSUE TITLE
Can I use this to create a quiz?

### ISSUE THREAD

**Issue by rmohan80** [jhlywa/chess.js#110]
I'm trying to work on a Learning Management System and one of the requirements is to have a chessboard with a tactical position.

Now, if the user moves the correct piece, then the user has gotten a point. If not then it should show that it's not the correct move and user doesn't get a point. (Somewhat like www.chesstempo.com but without all the ratings and things like that).

Off course the other requirement is more complicated positions where the position might be a 2 move puzzle, so if the user makes the correct move, I need to make a move on the board and again ask user to move the piece for the 2nd move and so on.

Just wondering if there is any way that this can be done? 

I do notice that there are .put() and .get(square) etc, but can these be programmed to describe what I'm asking for?

**Comment by RySchmitt** [comment]
This sounds fairly simple to do. You can use chessboard.js and chess.js together out of the box. If you modify [this example](http://chessboardjs.com/examples#5000), just use load_pgn to load up the tactic position and modify the the onDrop function to see if the chosen move is the correct move. If it is, use the move function to add the reply.

**Comment by jhlywa** [comment]
I agree with @RySchmitt , it should be pretty straight forward.  However, I would recommend using `chess.load('rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')` to load a specific position instead of `chess.load_pgn(...)` which loads an entire game.
