### ISSUE TITLE
Problem loading PGN with ambiguous moves

### ISSUE THREAD

**Issue by sdemingo** [jhlywa/chess.js#117]
Hi,

I have a problem when I try to load the following game with the `.load_pgn` even using `{sloppy:true}` as option. I think that the white's movements 27 and 28 are ambiguities and I don't know if they are well notated. 

[Event "AI Factory's Chess"]
[Site "Android Device"]
[Date "2016.06.06"]
[Round "1"]
[White "T?"]
[Black "Cpu (3)"]
[PlyCount "59"]
[Result "1-0"]

1. e4 e5 2. Nf3 d5 3. Nxe5 f6 4. Bb5+ c6 5. Qh5+ Ke7 
6. Qf7+ Kd6 7. d3 Kxe5 8. Qh5+ g5 9. g3 cxb5 10. Bf4+ Ke6 
11. exd5+ Qxd5 12. Qe8+ Kf5 13. Rg1 gxf4 14. Nc3 Qc5 15. Ne4 Qxf2+ 
16. Kxf2 fxg3+ 17. Rxg3 Nd7 18. Qh5+ Ke6 19. Qe8+ Kd5 20. Rg4 Rb8 
21. c4+ Kc6 22. Qe6+ Kc7 23. cxb5 Ne7 24. Rc1+ Kd8 25. Nxf6 Ra8 
26. Kf1 Rb8 27. Rc1c4 b6 28. Rc4d4 Rb7 29. Qf7 Rc7 30. Qe8#  1-0

The PGN was produced by an Android App called Free Chess from AI Factory Limited and I'm using to parse it chess.js version 0.10.0

**Comment by jhlywa** [comment]
The move `27. Rc1c4` should be written as `27. Rcc4`.  I've got a few ideas on how to handle these.  Stay tuned.

**Comment by jhlywa** [comment]
This should be fixed in v0.10.2.

**Comment by sdemingo** [comment]
It's works! 

Thanks
