### ISSUE TITLE
Game stuck with no moves left

### ISSUE THREAD

**Issue by danwit** [jhlywa/chess.js#125]
While fiddling around I got into this situation in which player white was in-check, had no valid moves left and therefore couldn't react on its turn.

![chess](https://cloud.githubusercontent.com/assets/1330413/18147681/17afc39c-6fd6-11e6-94ce-777c45e231d5.png)

`chess.history()` got me:
`["e4", "f5", "exf5", "e5", "f6", "Kf7", "f4", "e4", "f5", "e3", "Ke2", "d5", "d3", "d4", "Kf3", "e2", "Ke4", "e1=R+", "Kf4", "Re3", "Kg4", "Re6", "Kg5", "Kg8", "Kg6", "Kf8", "Kh7", "Re4", "Kh8", "Rh4#"]`

Could this be something I have to check for myself or is there something else I'm missing?

**Comment by jhlywa** [comment]
White is checkmated.  `chess.game_over()` should return `true`.
