### ISSUE TITLE
missing legal moves in response to call of moves fuction

### ISSUE THREAD

**Issue by oddskill** [jhlywa/chess.js#127]
edit: just noted that the error occurs because chess.js doesnt read some fens.
"8/8/1k6/8/4Q3/7K/8/8 w - -" ie isnt read at all

**Comment by oddskill** [comment]
on hold: doing more testing

**Comment by oddskill** [comment]
Likewise when using 'rnbqkbnr/pppppppp/8/8/8/8/8/4K2R w KQkq -' as input string.
a call to moves(); returns an empty array.

**Comment by jhlywa** [comment]
You need to add the half_move and move counter to make the FEN valid: `8/8/1k6/8/4Q3/7K/8/8 w - - 0 1`

**Comment by oddskill** [comment]
Tyvm for pointing it out, my fault, sry for wasting your time.

Best regards

Chris
