### ISSUE TITLE
Castling Issue

### ISSUE THREAD

**Issue by EarlRussellJr** [jhlywa/chess.js#128]
Hello - I am using Chess.js with Chessboard.js and have an issue with castling.

I play this opening set of moves on chessboard.js and the castle move only moves the King and not the Rook.

Ruy Lopez Open
1.e4 e5 2.f3 c6 3.b5 a6 4.a4 f6 5.O-O xe4

Chess.js translates to:

e2-e4 e7-e5
g1-f3 b8-c6
f1-b5 a7-a6
b5-a4 g8-f6
e1-g1 f6-e4
Upon move 5 for white, o-o, the actual move should be e1-g1, h1-f1 for white.

When I modify the code to catch a Kingside Castle (looking for 'e1-g1' string) I pass this for the move:
board.move('e1-g1', 'h1-f1');
This is input from chessboard.js.  The code works and the castling happens.

However, at this point chess.js loses the sequence for whose move it is.  It should now be black's turn in this example but chess.js has counted the castle as a white and black move and wants to move the white pieces for the next move.

Is there a way to pass a flag to tell chess.js not to count the castle as two moves?  Or is there a way to toggle whose move it is within chess.js?

Thank you,
Earl Russell

**Comment by jhlywa** [comment]
The move generation code in chess.js is pretty well tested, so I suspect this bug has something to do with your chessboard.js integration.  How does your code compare to http://chessboardjs.com/examples#5000?

**Comment by EarlRussellJr** [comment]
Thank you for your response.  Earlier today I responded and tried to close
the issue but the page denied me and closed.  I cleared the browser cache
and ran tests again and discovered I had no issue.  Sorry for the false
alarm.
