### ISSUE TITLE
Loading PGN data containing SetUp and FEN tags causes header information to be lost

### ISSUE THREAD

**Issue by siansell** [jhlywa/chess.js#129]
The `load(headers['FEN'])` call [on this line](https://github.com/jhlywa/chess.js/blob/master/chess.js#L1451) in turn calls `clear()`, which loses the header information that has already been read in `load_pgn()`. Subsequently calling `header()` on the Chess object returns only SetUp, FEN and Result headers - other tags from the PGN data are lost.

A fix would be to conditionally not reset the header information in `clear()`, but I don't know if this would have any side effects?

**Comment by jhlywa** [comment]
Thanks for the precise report.  That's definitely a bug.  I'll push a fix out sometime this weekend.

**Comment by siansell** [comment]
Will you accept a pull request for this? I'm working from a fork right now.

**Comment by jhlywa** [comment]
Absolutely, as long as the PR includes a few tests.

**Comment by jhlywa** [comment]
Fixed in #154
