### ISSUE TITLE
Updating chess to shatranj

### ISSUE THREAD

**Issue by adarshks** [jhlywa/chess.js#135]
Shatranj is an old form of chess in which the queen and bishop have different type of movements. I have changed their movements by editing the piece offsets. but there comes a problem when checking the condition of "king_attacked" when a move is made but it is still checking that condition using the queens old movements.How can i change that in the "attacked" function according to the new movements.

the new form of piece offset is 

var PIECE_OFFSETS = {
    n: [-18, -33, -31, -14,  18, 33, 31,  14],
    b: [-34, -30,  34,  30],
    r: [-16,   1,  16,  -1],
    q: [-17, -15,  17,  15],
    k: [-17, -16, -15,   1,  17, 16, 15,  -1]
  };

Can you help me??

**Comment by jhlywa** [comment]
chess.js uses something called 0x88 move generation, so it's requires a few updates to handle different piece types.

You're going to have to update the `ATTACKS` table (and possibly the `RAYS` table, I don't know the rules for shatranj) to handle the new piece movement.  The `ATTACKS` table is a bit-mask of pieces (see `SHIFTS`) that can attack the center `0` square.  The `RAYS` table holds the offset to apply to the 128 square board to move in a piece in a particular direction.

See https://chessprogramming.wikispaces.com/0x88 for more info.

**Comment by ajithrpai** [comment]
Thaku for the feedback..
