### ISSUE TITLE
Header gets lost when loading FEN

### ISSUE THREAD

**Issue by tk1** [jhlywa/chess.js#139]
Take the following example PGN:

[White "test1"]
[Black "test2"]
[Result "1/2-1/2"]
[SetUp "1"]
[FEN "7K/8/7k/8/8/8/5q2/8 b - - 0 1"]
[PlyCount "1"]

1... Qf7 1/2-1/2

If loaded by load_pgn, the headers will be parsed and set, but then get lost, because in load(fen) the function clear() is called.

**Comment by jhlywa** [comment]
Known bug. Duplicate of #129
