### ISSUE TITLE
There is no "board()" method in 0.10.2

### ISSUE THREAD

**Issue by BillyWM** [jhlywa/chess.js#140]
Might want to update the documentation. It's not clear that this is from a future release. Pulled down the library from NPM and was very confused for a minute.

**Comment by rich-earth** [comment]
Had the same problem grabbing it from npm, but the method is there in github version. Wonder if npm is pulling down a different branch?

**Comment by jhlywa** [comment]
How do other libraries handle this?  I've always switched to the tag of the release in question to get the appropriate documentation.

**Comment by mhink** [comment]
@jhlywa I'm pretty sure the way to go would be to publish `10.3.0-alpha.1`, or something like that. That makes it a bit easier for folks to try out the new API, while still communicating that it's not stable yet.

**Comment by DoumanAsh** [comment]
Well, you can always pull npm dependency from github `git@github.com:jhlywa/chess.js.git#master` if you want to get latest stuff

**Comment by ZaninDavide** [comment]
This code uses chess.ascii() to get the piece you want. I think you can you it instead. It doesn't return an array but you can change it.
`
getPieceRender(letter, number, board) { // board = chess.board()
        let dict = { 1: "a", 2: "b", 3: "c", 4: "d", 5: "e", 6: "f", 7: "g", 8: "h", }
        let finalLetter = typeof letter === "number" ? dict[letter] : letter;
        let pos = (8 - number + 1) * 30 + 5 + 3 * (finalLetter - 1);
        let piece = board[pos];
        if (piece !== ".") {
            return piece;
        } else {
            return "empty"
}
`

**Comment by dax006** [comment]
It's there in the public API... so why can't we call it?!?

```

   board: function() {
      var output = [],
        row = [];

      for (var i = SQUARES.a8; i <= SQUARES.h1; i++) {
        if (board[i] == null) {
          row.push(null);
        } else {
          row.push({ type: board[i].type, color: board[i].color });
        }
        if ((i + 1) & 0x88) {
          output.push(row);
          row = [];
          i += 8;
        }
      }

      return output;
    },
```

**Comment by obipawan** [comment]
I believe @jhlywa hasn't made a new release yet with the latest additions.
For the time being, you need to add the dependency as such
```
"dependencies": {
    "chess.js": "github:jhlywa/chess.js",
    ...
}
```

**Comment by jhlywa** [comment]
The latest version has been pushed to NPM
