### ISSUE TITLE
Board size

### ISSUE THREAD

**Issue by desislavsd** [jhlywa/chess.js#147]
I have a special case that I need to apply the lib against board with different dimensions, 5x5 for example. Is   it currently possible or is it hard to implement. Hope it is easy. Thanks!

**Comment by kodejuice** [comment]
That's impossible, chess.js was solely built for standard chess (8x8) board, and i haven't heard of a variation of chess that uses a (5x5) board. You could build your own library that supports whatever you want to achieve, implement how you want the pieces to move and all.

**Comment by desislavsd** [comment]
Hah, sry for making you feel confused, I know it's a special case and you are right - there is no variation with different board size... Yet! 
Anyway, thanks for the quick response! Best!

**Comment by tylerxprice** [comment]
CT-ART, for example, will show you a small 5x5 board that simplifies the concept that the tactic uses.
