### ISSUE TITLE
setup new rules

### ISSUE THREAD

**Issue by gultekinmg** [jhlywa/chess.js#155]
since i believe standart chess rules are illogical and unsatisfactory/ i want to develop new rules for non stalemate chess.

imitation is simple: i should have been enabled to capture my own pieces to gather positional advantage or avoid king mated because stalled by own pieces. 
Also avoid stalemate that my opponent should capture his own pieces to move so if no other move. stalemate could becounted as a lost/

is it too complex for your code??

**Comment by questsin** [comment]
Sounds like an idea for a variant. You need to allow for capturing your own men. This would mess up alot of game variant engines. Most variant engines allow for specialized piece movement like [fairymax](http://home.hccnet.nl/h.g.muller/CVfairy.html). Not for specialized rules. If you always allow capturing your own men, forking chess.js would be relatively easy. However AI's need to be aware of these new possible moves. You could still have a statemate at the end... two kings or insufficient material :(

**Comment by gultekinmg** [comment]
two kings or insufficient material is not stalemate\ it is a legal draw not like stalemate/

**Comment by gultekinmg** [comment]
dude please, all traditional chess rules are faulty, 
This is a great step for humanity,
perform this task if you can,
Earth Life depend on this,

**Comment by questsin** [comment]
I played by these rules and the dynamics were fun. Like 3-check variant.
Your pieces can sack your own pawns for quick tactical play. Game should be
called "Collateral damage". I'm working on moding chess.js to support the
rules.

**Comment by gultekinmg** [comment]
talking about unlogical rules/
all pawns should only promote to pieces which pieces they took place. 
But promoting queen and king are not allowed due to royality principles. how many queen and king admin a state? imagine promoting 8 kings to mate seperately/ why they have let too many queens at a game while not king???
it is very well know that all seconds have fight back their own land at history.
let chess be logical. not a nonsense wood pushing rule game.

**Comment by gultekinmg** [comment]
i know u cant mass with this. it is not easy change all algorythms. That means new rules leads more complicated chess for human than usual stupid standard chess. a KING should never get mated or stalled by own pieces that suck. and it is written nolawns you cant eat your own pieces.
