### ISSUE TITLE
Fen not loading

### ISSUE THREAD

**Issue by pavelZem** [jhlywa/chess.js#165]
I load fen through a method load, but on an output I receive default fen. 
`var chess = new Chess();
chess.load("rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq -");
console.log(chess.fen()); // output -> rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
`
what am I doing wrong?

**Comment by jhlywa** [comment]
You need the full FEN which includes move numbers: `rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1`

**Comment by pavelZem** [comment]
Thanks.
