### ISSUE TITLE
About in_checkmate() with Ka7 or Ka8

### ISSUE THREAD

**Issue by UserFro** [jhlywa/chess.js#168]
Hello, why this is a true:
```
var game = new Chess ('k7/2Q5/8/8/8/8/8/8 w - - 0 1');
alert (game.in_checkmate()); //true
```

but for any similar position returned value is false:
```
var game = new Chess ('7k/5Q2/8/8/8/8/8/8 w - - 0 1');
alert (game.in_checkmate()); //false
```

Only for positions with king on a7 or a8 (and without opposite king on the board) the function says "true" and i can't get moves() array for any piece.

**Comment by jhlywa** [comment]
It's not a valid position, you need a white king on the board.

**Comment by UserFro** [comment]
Of course. But there are different ways to use the API. I am confused by the difference of the function logic
