### ISSUE TITLE
Get position of piece

### ISSUE THREAD

**Issue by knownasilya** [jhlywa/chess.js#174]
Is there an API for getting the position of a piece? Like `chess.position({ type: 'k', color: 'w' }) // e5`
Also the moves that a piece can make or from a position (once we have that).

**Comment by hassan-c** [comment]
To get the position(s) of piece(s), something like the following works. This takes the piece as a parameter in the form of an object like `{ type: 'k', color: 'w'}` and returns an array of all the squares that pieces with that colour and type currently occupy. For a white king in the initial starting position, it would just return `['e2']`.

`const get_piece_positions = (game, piece) => {
  return [].concat(...chess.board()).map((p, index) => {
    if (p !== null && p.type === piece.type && p.color === piece.color) {
      return index
    }
  }).filter(Number.isInteger).map((piece_index) => {
    const row = 'abcdefgh'[piece_index % 8]
    const column = Math.ceil((64 - piece_index) / 8)
    return row + column
  })
}
`

And to obtain all currently legal moves, given a piece type and colour, the following will return an array of legal moves in SAN format.

`const get_legal_moves_by_piece = (game, piece) => {
  return chess.moves({ verbose: true })
              .filter((move) => move.piece === piece.type && move.color === piece.color)
              .map((move) => move.san)
}`

**Comment by CleverProgrammer** [comment]
@hassan-c thank you for sharing this! That code worked like magic 🎉!!

**Comment by knownasilya** [comment]
@hassan-c is that last code snippet basically `chess.moves({ square: 'e2' })` but also filtered on `from`?

**Comment by hassan-c** [comment]
@knownasilya Yes, I believe so. `chess.moves({ square: 'e2'})` probably works better actually - I hadn't spotted that option. For example, `get_legal_moves_by_piece(chess, {type:'p', color:'w'})` will return an array of 16 moves, i.e. all possible pawn moves, which is probably not what you wanted actually. You could add another filter to my function but at that point you'd just be best off using `chess.moves({'square': 'e2'})` as you mention.

**Comment by 2kama** [comment]
`
const get_piece_position = ( piece: { type: string, color: string} ) => {
    let squares: string[] = [];
      game.board().map(row => {
        row.map(p => {
            if (p?.color === piece.color && p?.type === piece.type) {
                squares.push(p.square)
            }
            
        })
    })
    return squares;
  }
`
