### ISSUE TITLE
Checking status of a king castling.

### ISSUE THREAD

**Issue by lu4** [jhlywa/chess.js#176]
Is there an API to check if either kings still have an option to castle, i.e. whether the move was made by a king or a rook?

**Comment by hassan-c** [comment]
There is not a function for it, but you can obtain that information from the FEN, for which there is a function.

**Comment by jhlywa** [comment]
Check the third field of the FEN string (https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation#Definition).
