### ISSUE TITLE
Update dev dependencies to fix vulnerabilities, commit package-lock.json, and fix test titles

### ISSUE THREAD

**Issue by tjadenad** [jhlywa/chess.js#181]
When running `npm install`, the audit fails due to multiple vulnerabilities in the devDependencies:

> $ npm install
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
> added 33 packages from 51 contributors and audited 33 packages in 5.726s
> found 6 vulnerabilities (3 low, 1 moderate, 1 high, 1 critical)
>   run `npm audit fix` to fix them, or `npm audit` for details

`npm audit` shows (summarized):

> $ npm audit
> ...
> \# Run  npm install --save-dev mocha@5.2.0  to resolve 4 vulnerabilities
> SEMVER WARNING: Recommended action is a potentially breaking change
> ...
> \# Run  npm install --save-dev uglify-js@3.4.7  to resolve 2 vulnerabilities
> SEMVER WARNING: Recommended action is a potentially breaking change
> ...
> found 6 vulnerabilities (3 low, 1 moderate, 1 high, 1 critical) in 33 scanned packages
>   6 vulnerabilities require semver-major dependency updates.

Updating these dependencies allows `npm install` to run successfully.  
However, two of the tests are passing in `number`s rather than `string`s to the `it()` method:
> $ npm test
> ...
> throw new Error(
> ^
> 
> Error: Test `title` should be a "string" but "number" was given instead.

Additionally, `package-lock.json` should be a committed file.  The [documentation](https://docs.npmjs.com/files/package-lock.json) reads:

> This file is intended to be committed into source repositories, and serves various purposes:
> 
>  - Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
> 
>  - Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.
> 
>  - To facilitate greater visibility of tree changes through readable source control diffs.
> 
>  - And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.
> 

Would you be interested in seeing a pull request to update the dependencies, commit package-lock.json, and fix these unit tests?

**Comment by jhlywa** [comment]
Thanks for the PR.  I migrated the test suite to something I'm more familiar with these days.  I also ended up dropping uglify.
