### ISSUE TITLE
Change the move of Pawn

### ISSUE THREAD

**Issue by Engineerumair** [jhlywa/chess.js#183]
I want different move for the pawn, because I need to build different game on the basis of existing library

**Comment by Engineerumair** [comment]
other game

**Comment by Engineerumair** [comment]
Could some one please let me know what is offset array used for and how it works?

**Comment by CharlesKumar** [comment]
>  what is offset array used for

I am not able to understand context of your question

if your other game is chess based (like chess 960)

Here's a tutorial on how square are calculated ([youtube video](https://www.youtube.com/watch?v=FsjIJMUIXLI))

>  difference from array index is called offsets in programming 

>  say array[index+offset]  like array[index+2}

learn javascript [arrays](https://www.joezimjs.com/javascript/get-started-javascript-arrays/), [multi-dimensional arrays](http://www.javascripttutorial.net/javascript-multidimensional-array/),

If your other game is other than chess 

use other suitable board engines like [boardgame.io](http://boardgame.io/#/tutorial)

**Comment by jhlywa** [comment]
chess.js uses the 0x88 move generation algorithm for efficiency - which uses an underlying 8x16 board.  `PAWN_OFFSETS` describes the possible pawn movements on this 8x16 board.  Be warned, changing any offsets requires changes to the `ATTACKS` array (and potentially the `RAYS` array if your changes aren't confined to the pawn).

**Comment by Engineerumair** [comment]
I need to change this 0x88 move generation algorithm I need to set different offset and I need just two kinds of pieces in whole board.

Could you please explain this line of code?
var DEFAULT_POSITION = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';

**Comment by CharlesKumar** [comment]
That's FEN notation for start position of a chess game

FEN notations represents the board position.

Here you can [read more](http://www.chessgames.com/fenhelp.html) [[wiki](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation)]

**Comment by Engineerumair** [comment]
@CharlesKumar  But what does the end of the string do (w KQkq - 0 1';)

**Comment by CharlesKumar** [comment]
w KQkq - 0 1';

w       - white to move (if b then black to move)
KQkq - (castling rights of white kingside (K), white queenside(Q), black kingside (k), black queenside (q)

\-       En passant target square (if a pawn moved 2 square then the target square is returned)

0       - half move (This is the number of halfmoves since the last capture or pawn advance. This is used to determine if a draw can be claimed under the fifty-move rule.)
1       - full move (represents the move number)

**Comment by CharlesKumar** [comment]
if you want to learn about move generation

Here's an [article](https://peterellisjones.com/posts/generating-legal-chess-moves-efficiently/) explaining legal moves

you could have watch more videos in the series to understand more from ([youtube series](https://www.youtube.com/watch?v=FsjIJMUIXLI))

**Comment by Engineerumair** [comment]
@CharlesKumar  I have set pawn offset to 16, 32, 1, -1 to have forward and left right movement but It only moves in forward direction not in left and right.
could you please help me in this regard?

**Comment by CharlesKumar** [comment]
try [this](http://chessboardjs.com/)

you can move piece anywhere you want
