### ISSUE TITLE
Changes In  0x88 Move Generation Algorithm for Pawn Movement

### ISSUE THREAD

**Issue by Engineerumair** [jhlywa/chess.js#184]
I need to change this 0x88 move generation algorithm I need to set different offset and I need just two kinds of pieces in whole board.

Could you please explain this line of code?
var DEFAULT_POSITION = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';

**Comment by ygator** [comment]
See [FEN Notation](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation)
