### ISSUE TITLE
Change The Turn Of the player when pawn reaches to end

### ISSUE THREAD

**Issue by Engineerumair** [jhlywa/chess.js#187]
I have changed the movement of the pawn to make turkish checker from this library.
Here is the new code for Pawn movement.

`   function build_move(board,pieceLocation, from, to, flags, captureLocation, promotion) {
        var move = {
           color: turn,
           from: from,
           to: to,
           flags: flags,
           piece: board[pieceLocation].type
       };

    if (promotion) {
        move.flags |= BITS.PROMOTION;
        move.promotion = promotion;
    }

    if (board[from + captureLocation]) {
        move.captured = board[from +captureLocation].type;
    } 
    else if (flags & BITS.EP_CAPTURE) {
        move.captured = PAWN;
    }
    return move;
}
function make_move(move) {
    var us = turn;
    var them = swap_color(us);
    push(move);

    board[move.to] = board[move.from];
        
    board[move.from] = null;

    /* if ep capture, remove the captured pawn */
    if (move.flags & BITS.EP_CAPTURE) {
        if (turn === BLACK) {
            board[move.to - 16] = null;
        } else {
            board[move.to + 16] = null;
        }
    }

    /* if pawn promotion, replace with new piece */
    if (move.flags & BITS.PROMOTION) {
        board[move.to] = {type: move.promotion, color: us};
    }

    /* if we moved the king */
    // umair - commented because we don't have king now
    //if (board[move.to].type === KING) {
    //    kings[board[move.to].color] = move.to;

    //    /* if we castled, move the rook next to the king */
    //    if (move.flags & BITS.KSIDE_CASTLE) {
    //        var castling_to = move.to - 1;
    //        var castling_from = move.to + 1;
    //        board[castling_to] = board[castling_from];
    //        board[castling_from] = null;
    //    } else if (move.flags & BITS.QSIDE_CASTLE) {
    //        var castling_to = move.to + 1;
    //        var castling_from = move.to - 2;
    //        board[castling_to] = board[castling_from];
    //        board[castling_from] = null;
    //    }

    //    /* turn off castling */
    //    castling[us] = '';
    //}

    ///* turn off castling if we move a rook */
    //if (castling[us]) {
    //    for (var i = 0, len = ROOKS[us].length; i < len; i++) {
    //        if (move.from === ROOKS[us][i].square &&
    //            castling[us] & ROOKS[us][i].flag) {
    //            castling[us] ^= ROOKS[us][i].flag;
    //            break;
    //        }
    //    }
    //}

    /* turn off castling if we capture a rook */
    // umair - commented because we don't have rook now
    //if (castling[them]) {
    //    for (var i = 0, len = ROOKS[them].length; i < len; i++) {
    //        if (move.to === ROOKS[them][i].square &&
    //            castling[them] & ROOKS[them][i].flag) {
    //            castling[them] ^= ROOKS[them][i].flag;
    //            break;
    //        }
    //    }
    //}

    /* if big pawn move, update the en passant square */
    if (move.flags & BITS.BIG_PAWN) {
        if (turn === 'b') {
            ep_square = move.to - 16;
        } else {
            ep_square = move.to + 16;
        }
    } else {
        ep_square = EMPTY;
    }

    /* reset the 50 move counter if a pawn is moved or a piece is captured */
    if (move.piece === PAWN) {
        half_moves = 0;
    } else if (move.flags & (BITS.CAPTURE | BITS.EP_CAPTURE)) {
        half_moves = 0;
    } else {
        half_moves++;
    }

    if (turn === BLACK) {
        move_number++;
    }
    var diff = move.to - move.from
    if ((diff == 32 || diff == -32) && ((board[move.to + diff] == undefined || board[move.to + diff] == null) && board[move.to + (diff / 2)] != null && !((move.to + (diff/2)) & 0x88))) {
        if (board[move.to + (diff / 2)].color === us) {
            turn = swap_color(turn);
        } 
    }
    else {
        turn = swap_color(turn);
    }
        
}

function undo_move() {
    var old = history.pop();
    if (old == null) { return null; }

    var move = old.move;
    kings = old.kings;
    turn = old.turn;
    castling = old.castling;
    ep_square = old.ep_square;
    half_moves = old.half_moves;
    move_number = old.move_number;

    var us = turn;
    var them = swap_color(turn);

    board[move.from] = board[move.to];
    //board[move.from].type = move.piece;  // to undo any promotions
    board[move.to] = null;

    if (move.flags & BITS.CAPTURE) {
        // commented because capture rule is changed
        //board[move.to] = { type: move.captured, color: them };
        // but this line doesn't work, if this is line is not commented then it shows again the captured piece
        // board[move.to + (diff/2)] = { type: move.captured, color: them };
            
    } else if (move.flags & BITS.EP_CAPTURE) {
        var index;
        if (us === BLACK) {
            index = move.to - 16;
        } else {
            index = move.to + 16;
        }
        board[index] = {type: PAWN, color: them};
    }

    return move;
}
function generate_moves(options) {

    function add_move(board, moves,pieceLocation, from, to, flags,capturedLocation) {
           
        moves.push(build_move(board,pieceLocation, from, to, flags, capturedLocation));
       
    }
    var moves = [];
    var us = turn;
    var them = swap_color(us);
    var second_rank = {b: RANK_7, w: RANK_2};

    var first_sq = SQUARES.a8;
    var last_sq = SQUARES.h1;
    var single_square = false;

    for (var i = first_sq; i <= last_sq; i++) {
        /* did we run off the end of the board */
        if (i & 0x88) { i += 7; continue; }

        var piece = board[i];
        if (piece == null || piece.color !== us) {
            continue;
        }

        if (piece.type === PAWN) {
            /* single square, non-capturing */
            for (var k = 0; k < 3; k++) {
                var square = i + PAWN_OFFSETS[us][k];
                if (board[square] == null) {
                    add_move(board, moves, i,i, square, BITS.NORMAL,0);

                    /* double square */

                }
            }
                
                

            /* pawn captures */
            for (j = 3; j < 6; j++) {
                var opponentOffset = PAWN_OFFSETS[us][j - 1];
                var opponentSq= i + opponentOffset;
                var offset = PAWN_OFFSETS[us][j];
                var jumpSq = i + offset;
                if (jumpSq & 0x88 || opponentSq & 0x88) continue;

                if (board[opponentSq] != null && (board[jumpSq] == null || board[jumpSq] == undefined)) {
                        
                    if (board[opponentSq].color === them) {
                        add_move(board, moves, i,(jumpSq - offset), jumpSq, BITS.CAPTURE, opponentOffset);
                    }
                    return moves;
                }
            }
                

            move: function(move, options) {
                /* The move function can be called with in the following parameters:
                 *
                 * .move('Nxb7')      <- where 'move' is a case-sensitive SAN string
                 *
                 * .move({ from: 'h7', <- where the 'move' is a move object (additional
                 *         to :'h8',      fields are ignored)
                 *         promotion: 'q',
                 *      })
                 */

                // allow the user to specify the sloppy move parser to work around over
                // disambiguation bugs in Fritz and Chessbase
                var sloppy = (typeof options !== 'undefined' && 'sloppy' in options) ?
                              options.sloppy : false;

                var move_obj = null;

                if (typeof move === 'string') {
                    move_obj = move_from_san(move, sloppy);
                } else if (typeof move === 'object') {
                    var moves = generate_moves();

                    /* convert the pretty move object to an ugly move object */
                    for (var i = 0, len = moves.length; i < len; i++) {
                        if (move.from === algebraic(moves[i].from) &&
                            move.to === algebraic(moves[i].to) &&
                            (!('promotion' in moves[i]) ||
                            move.promotion === moves[i].promotion)) {
                            move_obj = moves[i];
                            break;
                        }
                    }
                }

                /* failed to find move */
                if (!move_obj) {
                    return null;
                }

                /* need to make a copy of move because we can't generate SAN after the
                 * move is made
                 */

                // umair - capture the pawn when move is 32
                var diff = move_obj.from - move_obj.to;
                if (diff == 32 ) {
                    if (move_obj.flags & BITS.CAPTURE && board[move_obj.from - 16] != null) {

                        if (board[move_obj.from - 16].color != move_obj.color) {
                            board[move_obj.from - 16] = null;
                        }
                    }
                }
                else if (diff == -32) {
                    if (move_obj.flags & BITS.CAPTURE && board[move_obj.from + 16] != null) {

                        if (board[move_obj.from + 16].color != move_obj.color) {
                            board[move_obj.from + 16] = null;
                        }
                    }
                }
            
                var pretty_move = make_pretty(move_obj);

                make_move(move_obj);

                return pretty_move;
            }; `

I am able to move the pawn and capture the opponent but I need that it change its turn when white reaches to end. I have implemented this in make_move method but it doesn't work.

Could someone please help? 
Thank you in advance.

**Comment by CharlesKumar** [comment]
ignore this comment if it is irrelevant 

https://www.youtube.com/watch?v=93o_Ad5C5Ds
.
.
.
https://www.youtube.com/watch?v=JcNRcKJ-vUE

**Comment by Engineerumair** [comment]
@CharlesKumar that is implemented in unity but I need to change the existing chess.js library to work on

**Comment by Engineerumair** [comment]
@CharlesKumar can you please explain how undo_move and make_move methods are working right now and how it captures opponent.
because after changing these methods it wasn't capturing opponent so I wrote logic before calling make_move method in move method to capture opponent which start working then.

**Comment by jhlywa** [comment]
I believe this is outside the scope of chess.js
