### ISSUE TITLE
Error parsing Date header

### ISSUE THREAD

**Issue by erral** [jhlywa/chess.js#191]
I have the following PGN file header:

```
[Event "I OPEN DANOBAT ELGOIBAR SUB2200"]
[Site "ELGOIBAR ESP"]
[Date "2018.10.11" ]
[Round "2"]
[White "Manso Marquez, Felix"]
[WhiteFideId "2224445"]
[Black "Fernandez Del Pozo, Anibal"]
[BlackFideId "2285584"]
[Result "*"]
[WhiteElo "2120"]
[BlackElo "1888"]
[PlyCount "0"]
[EventDate "2018.09.27"]
[SourceDate ""]
```

When parsing it with chess.js, it does not fully parse the date:

- chess.load_pgn(value);
- chess.header('Date')
[Date "[Date "2018.10.11" ]"]

I was expecting:

- chess.header('Date')
2018.10.11

But it parses correctly if the date is written in ISO format (2018-11-20 instead of 2018.11.20).

**Comment by jhlywa** [comment]
Thanks for the report. For the time being you can work around this by removing the space the between quote and the square bracket (e.g. `" ]` to `"]`) in the date field.

**Comment by erral** [comment]
I see where the error is: my Date header has a whitespace just before the closing bracket. I don't know if that's just an error in my PGN file or the parser should handle this. If so, I can add a PR adding the support for such whitespaces to the regex that parses the header.

**Comment by jhlywa** [comment]
Thank you.  I'll merge as soon as I fix the tests in the master branch (for some reason, tests are failing with node 0.10)
