### ISSUE TITLE
chess.js in Angular 7

### ISSUE THREAD

**Issue by digither** [jhlywa/chess.js#208]
I try to import chess-js to angular 7 with this type:
1º npm i @types/chess.js  . With this way the error is : chess_js__WEBPACK_IMPORTED_MODULE_2__.Chess is not a constructor 
. This error is in @types/chess.js/index.d.ts in declaration of Chess 
```
export const Chess: {

    (fen?: string): ChessInstance;

    new (fen?: string): ChessInstance;
};
```
2º I try https://github.com/jhlywa/chess.js/pull/167/commits/89e9ea6f98756e21c3e1ed075cb0d867ddab6b13 like the test file
 
```
import * as ChessJs from 'chess.js';
import { Chess } from 'chess.js';

    let chess = new ChessJs.Chess();
    console.log(chess.ascii());
```

and this error and other:

```
ERROR in src/app/modulos_lichess/play.ts(2,17): error TS2305: Module '"chess.js"' has no exported member 'ChessInstance'.
src/app/modulos_lichess/play.ts(81,23): error TS2339: Property 'san' does not exist on type 'string | VerboseMove'.
```

Has anyone succeeded in importing chess.j to angular?

**Comment by supertorpe** [comment]
I've used chess.js in an ionic 4 / angular 7 project (without type defs) : https://github.com/supertorpe/chessendgametraining

**Comment by raphaelfruneaux** [comment]
@digither i was having the same issue when i was trying to import `chess.js` to vue.js application.
I tried to add the `@types/chess.js` and create my own declaration, but i didn't get success in those ways.

I solved my problem using the following import:
```ts
const Chess = require('chess.js');
```

So i can call the constructor:
```ts
const chess = new Chess();
console.log(chess.ascii());
```

**Comment by ildar-icoosoft** [comment]
it happens because of this code in https://github.com/jhlywa/chess.js/blob/master/chess.js:

```
/* export Chess object if using node or any other CommonJS compatible
 * environment */
if (typeof exports !== 'undefined') exports.Chess = Chess
/* export Chess object for any RequireJS compatible environment */
if (typeof define !== 'undefined')
  define(function() {
    return Chess
  })
```

Webpack supports both exports and define. So if you use webpack "Chess" will be imported as default.

So you could do:
`import Chess from "chess.js";`

But then it will not match the type definitions in "@types/chess.js". Instead, I suggest disable AMD in webpack config:

```
{
  test: /chess.js/,
  parser: {
    amd: false,
  },
},
```
