### ISSUE TITLE
Pawn Capture Flag is "cp", not "pc"

### ISSUE THREAD

**Issue by ghost** [jhlywa/chess.js#211]
On the README, it says that the flag for pawn captures is "pc". It appears that that is incorrect, and the flag is "cp". This caused me a lot of headaches as I tried checking for a "pc" flag when in fact I should have been checking for "cp".

Should be a very easy fix on the README :)

**Comment by Nicals** [comment]
According to [The readme](https://github.com/jhlywa/chess.js#moves-options-), *c* is the flag for *standard capture*, and *p* is the flag for *promotion*.

A *pc* flag is for promotion with pawn capture. The order of the letters in the flag is not relevant.
