### ISSUE TITLE
Make a move by clicking on notation.

### ISSUE THREAD

**Issue by karthikeyan-krishna** [jhlywa/chess.js#224]
Hi, Is there any possible way to make moves by clicking on a move (from a provided PGN) similar to ChessBase. The PGN might contain sub-variations also.

**Comment by GMPrakhar** [comment]
Since this is an API, without any user interface, you have to tackle that on your side. I would suggest loading the pgn and calling all the moves by `.move()` until the move you want ( or where user have clicked ).
