### ISSUE TITLE
chess.moves() not working for some valid squares.

### ISSUE THREAD

**Issue by franknmungai** [jhlywa/chess.js#229]
For a starting fen notation, `chess.moves({ square: 'a7' }) `returns an empty array. Shouldn't it Instead should have two elements for the two possible positions for the pawn at a7 ?

**Comment by Oreilles** [comment]
`a7` is a black pawn, and since it is whites' turn to play on the first move there is no _possible_ moves for blacks.

**Comment by franknmungai** [comment]
Thanks. I was previously using `chess.put() `and `chess.remove()` for my moves but I just noticed that it wasn't updating the `chess.turn `in the fen. I just switched to chess.move() and now it's working fine.
