### ISSUE TITLE
chess.move issue

### ISSUE THREAD

**Issue by Allirey** [jhlywa/chess.js#231]
In situation when 2 pieces can move on same square and one of them pinned - Move function can't recognize san move like Nge2 when correct of course is Ne2. 
test position: r1bqk1nr/ppp2ppp/2n5/3p4/1b1P4/2NB4/PPP2PPP/R1BQK1NR w KQkq - 2 6
e4 e6 d4 d5 Nc3 Bb4 exd4 exd4 Bd3 Nc6 and here Nge2 can't be recognized. It is very unpleasant, because some big guys in chess world like chessbase.com write it as Nge2, but lichess write it as Ne2.
Is it possible to fix parse of both variation of moves in such situations?

**Comment by jhlywa** [comment]
You can try using the sloppy parser option: `move('Nge2', {sloppy: true})`?

**Comment by Allirey** [comment]
Wow, thx, it works now
