### ISSUE TITLE
Half-move clock in FEN after immediate lost of a castling right

### ISSUE THREAD

**Issue by rontant** [jhlywa/chess.js#241]
Using the chess.fen() function, I found some inconsistency on the FEN it returns. It looks like the HALF-MOVE CLOCK field in FEN is not reset following a loss of castling right.

1. FEN before: r1bq1rk1/pp1pbppp/2n2n2/2p1p3/2B1P3/2NP1N1P/PPP2PP1/R1BQK2R w KQ - 1 7
2. Move e1-g1 (Castling)
3. FEN after:  r1bq1rk1/pp1pbppp/2n2n2/2p1p3/2B1P3/2NP1N1P/PPP2PP1/R1BQ1RK1 b - - 2 7

Shouldn't the half-move clock be reset to 0? 

Refer to this site:

> The Halfmove Clock inside an chess position object takes care of enforcing the fifty-move rule. This counter is reset after captures or pawn moves, and incremented otherwise. **Also moves which lose the castling rights, that is rook- and king moves from their initial squares, including castling itself, increment the Halfmove Clock.** However, those moves are irreversible in the sense to reverse the same rights - since once a castling right is lost, it is lost forever, as considered in detecting repetitions.

Reference: https://www.chessprogramming.org/Halfmove_Clock

**Comment by ajax333221** [comment]
The text in bold says those kind of moves increment the Halfmove Clock, and the fen in 1 and 3 have an increment in the Halfmove clock, everything is working as expected it seems.
