### ISSUE TITLE
Publish standard modules to npm

### ISSUE THREAD

**Issue by justinfagnani** [jhlywa/chess.js#246]
It would make it a lot easier to consume this library from standard JS modules if it were also published as JS modules.

Module support is extremely good across current JS environments. All major browsers have supported modules for years, and Node has supported them in the last 3 major versions, and soon to be the last 4 majors and last 2 LTS's. All bundlers also automatically support consuming dependencies published as modules and will convert them to whatever output format the user chooses.

**Comment by justinfagnani** [comment]
Any chance of this happening? Not being published as JS modules makes it difficult to use from projects that only use standard modules.

**Comment by justinfagnani** [comment]
I'd happily make a PR for this too.

**Comment by jhlywa** [comment]
@justinfagnani  Yes, can you submit a PR?  Thanks

**Comment by justinfagnani** [comment]
@jhlywa I have one incoming!
