### ISSUE TITLE
No possible move to WHITE with fen rnb2bnr/8/8/8/8/8/8/RNB2BNR w - - 0 1

### ISSUE THREAD

**Issue by kopeclu2** [jhlywa/chess.js#251]
Hi please could you help me ? 
I load this fen, Black color is on turn rnb2bnr/8/8/8/8/8/8/RNB2BNR b - - 0 1, normal possible moves for all pieces.
BUT for rnb2bnr/8/8/8/8/8/8/RNB2BNR w - - 0 1 only one move i aviable :

<img width="190" alt="Snímek obrazovky 2020-11-25 v 23 21 14" src="https://user-images.githubusercontent.com/43535871/100287429-eb942b00-2f74-11eb-8eb6-fc25c44c874c.png">
I dont knwo why it is working for black color and for white no...
Thank you so much

WHITE init turn [ERROR ]
<img width="542" alt="Snímek obrazovky 2020-11-25 v 23 23 08" src="https://user-images.githubusercontent.com/43535871/100287582-2f873000-2f75-11eb-9e6c-2f1278aa427c.png">

BLACK init turn [RIGHT]
<img width="542" alt="Snímek obrazovky 2020-11-25 v 23 22 38" src="https://user-images.githubusercontent.com/43535871/100287543-1da58d00-2f75-11eb-8392-0815bade0f84.png">

**Comment by jhlywa** [comment]
You need to place kings for both sides on the board.  chess.js only runs on valid positions.
