### ISSUE TITLE
Displaying in a UCI notation

### ISSUE THREAD

**Issue by crne24** [jhlywa/chess.js#256]
I wonder, would it be possible to switch between UCI and Algebraic?

**Comment by crne24** [comment]
Got it to work. For anyone wondering, that would be using the .from and the .to on chess.move. 

Example code:
```
const { Chess } = require('chess.js');
const chess = new Chess();
console.log(chess.move('e4').from);
```

Returns:
`e2`

**Comment by honkskillet** [comment]
Does UCI want a long algebraic notation?
ie `e2e4`
