### ISSUE TITLE
Danger detection

### ISSUE THREAD

**Issue by Novabllast** [jhlywa/chess.js#257]
Hello, thanks for your great work.

Is it possible to get all figures which are in danger of being captured by an other figure?

For example if white moves his queen, i want all field/figures which are in danger of being captured by the queen.

**Comment by void4** [comment]
This code may contain some of what you are looking for: https://github.com/vitogit/vue-chessboard/blob/master/src/components/chessboard/index.vue
(specifically countThreats and paintThreats)

**Comment by jhlywa** [comment]
Using the diagram provided by @void4, I believe `chess.moves({square: 'e3'. verbose: true})` is what you're looking for.
