### ISSUE TITLE
generate uci moves for use with engines like stockfish

### ISSUE THREAD

**Issue by honkskillet** [jhlywa/chess.js#259]
The common uci protocol users a type of long algebraic notation for moves.

> //Sending to Stockfish
> position startpos moves e2e3 d7d6 d1f3 b8d7 f1c4 e7e6 d2d4 d6d5
> 

It would be nice to be able to have a uciMove field on move objects.  As well as being able to get the full list of moves in UCI format.

I think this would generate a uci move from the current verbose move object.

> export function getLongAlgebraicNotationFromMoveObject (moveObj) {  
>   return (moveObj.promotion) 
>       ? moveObj.from+moveObj.to+moveObj.promotion //when there is a promotion
>       : moveObj.from+moveObj.to;
> }

**Comment by jhlywa** [comment]
Added a `lan` field (Long Algebraic Notation) to move objects in master.
