### ISSUE TITLE
[Question] .history() returns empty array

### ISSUE THREAD

**Issue by ExtremeCoolDude** [jhlywa/chess.js#266]
When I do` .load_pgn()` on this, I get empty array on` .history()`. Can anyone tell me  please how do I properly sanitize messy pgns like this one ?

Headers are trimmed in chess.js itself and seems special characters are escaped too, I cannot find what's wrong with this. Passing only the mainline SAN works though. 

```
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]
[FEN "r3kb1r/pbq2ppp/2p2n2/1pn1pP2/4P1P1/2NB1Q2/PPPBN2P/R3K2R w KQkq - 0 1"]
[Setup "1"]

1. a4 { [%csl Rh1,Ra8,Gf6,Gc5,Gc3,Gb5,Yb4,Yb7,Yc6,Ra1,Rg2,Rf3,Re4,Rd5][%cal
Gf6e4,Gc5e4,Gc3d1,Gd1f2,Rb7e4,Re4h1,Rg4g5,Rf6d7]}  ( 1. g5)1... b4 2. Nd1 Nfxe4
3. Bxe4 Nxe4 4. Qxe4 c5 5. Qc4 Bxh1 6. Bxb4 Be7 7. Ne3 O-O 8. O-O-O Bf3 9. Nd5
Qb7 10. f6 Bxd5 11. Qxd5 Qxd5 12. Rxd5 gxf6 13. Bxc5 Rfd8 14. Rxd8+ Bxd8 15. b4
h5 16. h3 hxg4 17. hxg4 Kg7 18. Ng3 Bb6 19. Be7 Kg6 20. c4 Bf2 21. Nf5 Kg5 22.
Nd6 Kxg4 23. c5 Kf3 24. c6 e4 25. c7 Bd4 26. Nb5 Be5 27. Bd6 e3 28. Bxe5 fxe5
29. Nd6 Kf2  *
```
```
console.log(pgn);
var fen = FEN;
chess = new Chess();
    var loadedpgn =  chess.load_pgn(pgn, {sloppy:true});
    var moveHistory =chess.history();
    console.log(moveHistory);
    console.log("hello world");

```

**Comment by ajax333221** [comment]
Try with `[SetUp "1"]` with uppercase U

**Comment by ExtremeCoolDude** [comment]
Thank you for the response.

No luck, I get [] array length = 0

Most of the time the moves must be plain like 1. a3 g4 2.b4 h7 or it returns empty array.

![image](https://user-images.githubusercontent.com/50034073/109242819-ee1c5000-7803-11eb-93f3-c4b7bff580f0.png)

**Comment by bhx4874** [comment]
ExtremeCoolDude I did a lot of testing and spent hours pouring through documentation only for the issue to be a missing empty string between the tag pair section and the movetext section.  I have no idea if you moved on to better projects, but I hope this still helps. Maybe someone can come along and tell me that I missed this in the README and that I could've saved hours of my life. 

![pgn](https://user-images.githubusercontent.com/42841990/115316820-22e3be00-a148-11eb-8573-848721f828f0.PNG)

**Comment by ExtremeCoolDude** [comment]
Thanks a lot @bhx4874 much appreciated. It was much more headache-less to parse pgn separately with entirely different tool  : https://github.com/mliebelt/pgn-parser and then only feed the "move" to chess.js.

**Comment by jhlywa** [comment]
@ExtremeCoolDude Maybe I'm missing something, but this appears to parse without issue for me:

```js
const { Chess } = require('./chess.js')
const chess = new Chess()                      
     
const moves = `[Event "?"]                          
[Site "?"]                               
[Date "????.??.??"]
[Round "?"]                                      
[White "?"]                             
[Black "?"]                                                                         
[Result "*"]                                                                      
[FEN "r3kb1r/pbq2ppp/2p2n2/1pn1pP2/4P1P1/2NB1Q2/PPPBN2P/R3K2R w KQkq - 0 1"]
[SetUp "1"]                                                                    
                                                                                   
1. a4 { [%csl Rh1,Ra8,Gf6,Gc5,Gc3,Gb5,Yb4,Yb7,Yc6,Ra1,Rg2,Rf3,Re4,Rd5][%cal        
Gf6e4,Gc5e4,Gc3d1,Gd1f2,Rb7e4,Re4h1,Rg4g5,Rf6d7]}  ( 1. g5)1... b4 2. Nd1 Nfxe4    
3. Bxe4 Nxe4 4. Qxe4 c5 5. Qc4 Bxh1 6. Bxb4 Be7 7. Ne3 O-O 8. O-O-O Bf3 9. Nd5    
Qb7 10. f6 Bxd5 11. Qxd5 Qxd5 12. Rxd5 gxf6 13. Bxc5 Rfd8 14. Rxd8+ Bxd8 15. b4  
h5 16. h3 hxg4 17. hxg4 Kg7 18. Ng3 Bb6 19. Be7 Kg6 20. c4 Bf2 21. Nf5 Kg5 22.      
Nd6 Kxg4 23. c5 Kf3 24. c6 e4 25. c7 Bd4 26. Nb5 Be5 27. Bd6 e3 28. Bxe5 fxe5       
29. Nd6 Kf2  *`                                                  
                                                     
chess.load_pgn(moves)                                                              
console.log(chess.history()) 
[
  'a4',   'b4',   'Nd1',   'Nfxe4', 'Bxe4', 'Nxe4',
  'Qxe4', 'c5',   'Qc4',   'Bxh1',  'Bxb4', 'Be7',
  'Ne3',  'O-O',  'O-O-O', 'Bf3',   'Nd5',  'Qb7',
  'f6',   'Bxd5', 'Qxd5',  'Qxd5',  'Rxd5', 'gxf6',
  'Bxc5', 'Rfd8', 'Rxd8+', 'Bxd8',  'b4',   'h5',
  'h3',   'hxg4', 'hxg4',  'Kg7',   'Ng3',  'Bb6',
  'Be7',  'Kg6',  'c4',    'Bf2',   'Nf5',  'Kg5',
  'Nd6',  'Kxg4', 'c5',    'Kf3',   'c6',   'e4',
  'c7',   'Bd4',  'Nb5',   'Be5',   'Bd6',  'e3',
  'Bxe5', 'fxe5', 'Nd6',   'Kf2'
]
```

**Comment by jhlywa** [comment]
@bhx4874 I'm sorry you ran into issues with the library. Maybe this requirement (the empty line between the Tag Pair and Movetext sections of the PGN file) is something we should add to an FAQ?

**Comment by ExtremeCoolDude** [comment]
Thanks a lot for the reply, creator jhlywa, much appreciated for this awesome lib. If someone stumbles onto this issue via google, use chess.js for only chess logic, use some library based on peg.js + grammar files to specify rules to parse pgn,  like the tool I mentioned above, will save you a lot of trouble.
