### ISSUE TITLE
Adding a new piece with custom movement rules

### ISSUE THREAD

**Issue by diego25061** [jhlywa/chess.js#267]
Is there any way to add a totally new piece? Say I'd like to add a knight instead of a horse that can jump further. Is this currently possible? Haven't found a way so far
Thanks in advance

**Comment by jhlywa** [comment]
You can definitely add a custom piece type to chess.js, but it's non-trivial.

First, the easy part, you'll need to add new piece/offsets to https://github.com/jhlywa/chess.js/blob/master/chess.js#L53-L59.  The offsets are relative to a 8x16 board used by the the internal [0x88 move generator](https://www.chessprogramming.org/0x88).  

Next, the hard part, you'll need to update the SHIFTS map and recompute the ATTACKS array, described here in section 2  https://github.com/jhlywa/chess.js/issues/230#issuecomment-599075007.
