### ISSUE TITLE
find all the squares where a piece is of a color

### ISSUE THREAD

**Issue by moblizeit** [jhlywa/chess.js#269]
I am looking for a way to find out all the squares a piece is currently on board. 

For example: all the black pawn squares  or all the white kings (sure there will be one only). 

So, ideally returning the array of positions for pawn like  ['a2','b2','c4']
for king like ['d4'] 

there is a reverse of it to get piece on a known square but above is what i need. any options?

**Comment by jhlywa** [comment]
Something like this should work:

```js
import { Chess, PAWN, WHITE } from './chess.js' 

const chess = Chess()

const squares = chess
  .board()
  .flat()
  .filter((piece) => {
    return piece?.type === PAWN && piece?.color === WHITE
  })
  .map(({ square }) => square)
```
