### ISSUE TITLE
Export the Chess class/object as default

### ISSUE THREAD

**Issue by pdigre** [jhlywa/chess.js#278]
export **default** const Chess: ....

I am unable to use "chess.js" with Typescript/ES6 because of "Object is not an instance" error when using Chess(fen).
The solution of using "require" rather than "import" as outlined in https://github.com/jhlywa/chess.js/issues/208 is not a good solution.

As a workaround I have patched it using yarn....

"dependencies": {
    "@types/chess.js": "patch:@types/chess.js@^0.10.1#./@types-chessjs.diff",

**@types-chessjs.diff**
diff --git a/index.d.ts b/index.d.ts
index 4bcfbb615729d9813c652303a773a9a043b21779..931d1cdd8cb88195c543e06e433b36034d197633 100644
--- a/index.d.ts
+++ b/index.d.ts
@@ -640,3 +640,5 @@ export const Chess: {
      */
     new (fen?: string): ChessInstance;
 };
+
+export default Chess;

**Comment by pdigre** [comment]
Here´s a workaround in the meantime.... 

// Just initialize differently to use Chess() as normal..
import { Chess as ChessImport, ChessInstance } from 'chess.js';
type ChessType = (fen?: string) => ChessInstance;
const ChessTemp = ChessImport as unknown;
const Chess = ChessTemp as ChessType;

**Comment by jhlywa** [comment]
This was fixed in 0.13.0
