### ISSUE TITLE
Should not accept fen with two white kings

### ISSUE THREAD

**Issue by loloof64** [jhlywa/chess.js#283]
The following fen has two white kings and no black king

```
8/2K5/8/8/2K1NB2/8/8/8 w - - 96 46
```

So I expect the framework to detect it as an illegal position and set the board fen to empty (`8/8/8/8/8/8/8/8 w - - 0 1`), like for other illegal positions. But it is not the case.

The position has been accepted and board set to this illegal position !

Indeed, when I check the [validate_fen](https://github.com/jhlywa/chess.js/blob/2d26ed8703b3eea57cfc1e6695fdb9f8253b2329/chess.js#L272) function, it seems that there is no check for the pieces count.

**Comment by cameronspeakflash** [comment]
Also should not accept pawns on ranks 1 and 8, or kings of opposite color touching:
8/8/8/8/8/1p6/8/6kK w - - 0 1

**Comment by jhlywa** [comment]
Thanks for the report. This issue has been fixed in the latest release (1.0.0-beta.1). The constructor and the `.load()` method now throw an exception with the message `Invalid FEN: too many white kings`
