### ISSUE TITLE
v0.12.0 allows "sloppy" moves that put own king in check

### ISSUE THREAD

**Issue by lesantoso** [jhlywa/chess.js#284]
For example,
```
chess.load('4k3/8/8/8/8/4p3/8/4K3 w - - 0 1')
chess.move('e1f2', { sloppy: true })
```
results in
`{ color: "w", flags: "n", from: "e1", piece: "k", san: "Kf2", to: "f2" }`.

(`null` is expected.)

**Comment by jhlywa** [comment]
Thanks for the report.  I've fixed the problem and added this test case to the regression tests.  Could you take things for a spin before I push to NPM?
