### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by piliugin-anton** [jhlywa/chess.js#288]
This FEN: 6k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 0
Shows that .game_over() = true and .in_draw() = true
Is it correct?

**Comment by ajax333221** [comment]
I think you should use `...0 1` like `6k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 0`

The Fullmove clock starts at 1, so that might be a problem if it finds a 0, but I don't know mm..

**Comment by jhlywa** [comment]
Yep `6k1/5ppp/8/8/8/8/5PPP/3R2K1 w - - 0 1` should work.  

I agree @ajax333221, there should be better errors when dealing with invalid FEN.  I'm working on a branch now that'll throw more meaningful exceptions in those cases.
