### ISSUE TITLE
Feature request: .move_is_promotion(move)

### ISSUE THREAD

**Issue by kurtjd** [jhlywa/chess.js#292]
I propose having a method that allows a user to check if a move results in promotion without having to actually perform the move. That way, the user can prompt a player for a piece to promote to.

Currently, the user would have to write this code themselves or using the API in a clunky manner, such as by performing a move, checking if it generates a promotion flag, undo the move, prompt player for promotion piece, then redo the move with the player’s input.

**Comment by fabthegreat** [comment]
Agree with that!
+1
