### ISSUE TITLE
Two square pawn moves generate fen with en passant square even when no pawn can capture.

### ISSUE THREAD

**Issue by noshir-patel** [jhlywa/chess.js#294]
This leads to problems with code that uses the fen to detect transpositions.

**Comment by noshir-patel** [comment]
One way to make this really clear to users of the library would be to support both fen and x-fen explicitly.  If you then use xfen internally for things like repetition detection, you get all the benefits without violating the pgn spec.  (For purposes of normal chess, I'm pretty sure the only difference between x-fen and fen is this one detail.)

**Comment by jhlywa** [comment]
The latest beta (1.0.0-beta.1) now uses **only_when_legal** logic when including the en passant square in the FEN output. Thank you all for your feedback.

**Comment by ethernetz** [comment]
I see that chess.com actually uses always now. Starting a game with 1. e4 gives this fen

rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1
https://www.chess.com/analysis/game/pgn/2PrJUsWxgW?tab=analysis

And also their documentation says 

_"Notice that the mere fact that a pawn has moved two squares implies that this indicator of a possible en passant capture would be present. The absence of enemy pawns threatening that capture does not influence this notation."_
https://www.chess.com/terms/fen-chess#en-passant-targets

**Comment by jhlywa** [comment]
I suppose we could make this an option in future versions ... e.g. 

```js
const chess = new Chess({ enPassantFenMode: 'always' })
```
