### ISSUE TITLE
Getting FEN strings of all possible next moves while in a given position

### ISSUE THREAD

**Issue by cinarli** [jhlywa/chess.js#296]
I want to get FEN strings of all possible next moves while in a current position. It doesn't happen with the "moves()" function. It returns as json. I want it in FEN strings format. So, let's say if the pawn can move from a3 to a4, I want the FEN string on the position at a4. Can you help?

**Comment by slashinfty** [comment]
For every possible move, make it, save the resulting FEN, then undo it.

```js
const fens = [];
const moves = chess.moves();
moves.forEach(move => {
    chess.move(move);
    fens.push(chess.fen());
    chess.undo();
});
```
