### ISSUE TITLE
chess.in_threefold_repetition() - not changing to true

### ISSUE THREAD

**Issue by bpalmer661** [jhlywa/chess.js#313]
I have moved the same piece on both of my screens , just back and forth to try and trigger chess.in_threefold_repetition() === true though it does not turn to true even after a lot more moves than 3

**Comment by jhlywa** [comment]
@bpalmer661 There are passing tests for three fold repetition in the test suite.  Can you provide a code sample showing this failing? 

```js
const chess = new Chess()

chess.move('Nf3')
chess.move('Nf6')
console.log(chess.in_threefold_repetition()) // <- false
chess.move('Ng1')
chess.move('Ng8')
console.log(chess.in_threefold_repetition()) // <- false
chess.move('Nf3')
chess.move('Nf6')
console.log(chess.in_threefold_repetition()) // <- false
chess.move('Ng1')
chess.move('Ng8')
console.log(chess.in_threefold_repetition()) // <- true
```
