### ISSUE TITLE
the option 'square' in move generation doesn't work?

### ISSUE THREAD

**Issue by Omshinwa** [jhlywa/chess.js#315]
Hi,

it's just always giving me back an empty array. I tried giving it a number or the square name. Am I using it wrong?

Sorry I'm kinda new to github.

**Comment by jhlywa** [comment]
Hi.  We've got tests for single square move generation in the test suite:  https://github.com/jhlywa/chess.js/blob/507189c83ce7b63adec4778ebdc09d454ecb5b09/__tests__/chess.test.js#L130-L135

If you're still having problems please post your code.
