### ISSUE TITLE
Confused by the result that get null in some partically promotion moves 

### ISSUE THREAD

**Issue by thanatos-proto** [jhlywa/chess.js#317]
+------------------------+
 8 | .  .  .  .  .  .  .  . |
 7 | .  .  .  P  .  .  .  . |
 6 | .  .  .  .  .  .  .  . |
 5 | .  .  .  .  .  .  .  . |
 4 | .  .  .  .  .  .  .  . |
 3 | .  .  .  .  b  .  .  . |
 2 | .  .  .  .  .  .  .  . |
 1 | .  .  .  .  .  .  .  . |
   +------------------------+
     a  b  c  d  e  f  g  h

In this case，when I want to make a promotion move , function move() returns null.
Why is it illegal ? 
Same result in this case

   +------------------------+
 8 | .  r  .  .  .  .  .  . |
 7 | .  .  .  P  .  .  .  . |
 6 | .  .  .  .  .  .  .  . |
 5 | .  .  .  .  .  .  .  . |
 4 | .  .  .  .  .  .  .  . |
 3 | .  .  .  .  .  .  .  . |
 2 | .  .  .  .  .  .  .  . |
 1 | .  .  .  .  .  .  .  . |
   +------------------------+
     a  b  c  d  e  f  g  h

**Comment by tissatussa** [comment]
i didn't ever use chess.js but i see you have no Kings on the board .. try a valid FEN (with 2 Kings) and try again.

**Comment by jhlywa** [comment]
@thanatos-proto Yes, you need valid position (e.g. both kings should be on the board).
