### ISSUE TITLE
move parsing issue v0.12.0 vs v0.13.0 (sloppy: true/false)

### ISSUE THREAD

**Issue by nevenca** [jhlywa/chess.js#321]
I am seeing an issue that is present since v0.12.0 which makes parsing of pgn games as generated by programs like ChessBase near impossible. Given the following examples:
const chess1 = new Chess('r4rk1/4nqpp/1p1p4/2pPpp2/bPP1P3/R1B1NQ2/P4PPP/1R4K1 w - - 0 28');
const chess2 = new Chess('rnbqk2r/p1pp1ppp/1p2pn2/8/1bPP4/2N1P3/PP3PPP/R1BQKBNR w KQkq - 0 5');
together with the moves:
let move1 = chess1.move('bxc5', { sloppy: true });
let move2 = chess2.move('Nge2', { sloppy: true });
the result is an error in the first example, i.e. no move is executed. If we change to:
let move1 = chess1.move('bxc5', { sloppy: false });
let move2 = chess2.move('Nge2', { sloppy: false });
the result is an error in the second example, i.e. no move is executed.

As per the spec, chess.js actually treats overly disambiguated moves correctly (kudos!) but in practice this makes parsing pgn output from a great many sources nearly impossible. The hugely popular ChessBase for example routinely disambiguates moves when not strictly necessary as per the second example above. Therefore successfully parsing a file generated by ChessBase requires { sloppy: true }, but that results in incorrectly flagging as problematic other cases, such as the first example where only { sloppy: false } works!

I am currently using the move_from_san() function code from v0.12.0 (almost unchanged) in v0.13.0 to get a "sane" version of sloppy move parsing back.

**Comment by jhlywa** [comment]
Thanks for the report @nevenca. I'll see what I can find.

**Comment by nevenca** [comment]
Thanks Jeff,

FYI, apologies if my choice of "sane" version of sloppy move parsing came across as unkind. That was not my intention. I have recently added chess.js (it's fabulous) for move checking and validation tasks in the last couple of versions of my own "chesskit" project displaying chess games online. The parser I built does RAVs and comments, and there are plenty of display options. An earlier version (without chess.js) is here:

https://neven.ca/chesskit


Regards, Neven

**Comment by jhlywa** [comment]
No offense taken @nevenca. I really do appreciate the report and I'm sorry for the regression. It looks like the breaking change was introduced in 0.12.1.

**Comment by jhlywa** [comment]
@nevenca This should be fixed now in master. Running with `{ sloppy: true }` will always try the strict parser first before falling back to sloppy. Can you give this a spin on your end? If things look good push, I'll push the fix to npm.

**Comment by nevenca** [comment]
Nice work! Everything looks good now at my end running tests on relevant sample data with `{ sloppy: true }`

**Comment by jhlywa** [comment]
0.13.1 has been published to npm

**Comment by neofight78** [comment]
In more recent versions the parameter has been changed to { strict: true } instead.
