### ISSUE TITLE
Many people having difficulties importing chess.js

### ISSUE THREAD

**Issue by Lode2** [jhlywa/chess.js#325]
As a beginner in webprogramming myself, I have had loads of trouble importing chess.js on multiple projects. A quick scan on stackoverflow tells me that I am not the only one with these issues. A couple responses on these questions do seem to work luckily, my suggestion however is to somehow fix these issues so the imports just always work, or to add something about this in the README, since this seemingly is a reocurring issue.

 I am not too familiar with all the technicalities involved in imports and nodejs modules etc so I don't know what is causing these issues, so I also don't know how to fix these issues. The link below leads to some questions, most of which are very similar, which describe some of the problems people are having in more detail:
https://stackoverflow.com/search?q=chess.js+import

I hope this is something that is useful to consider investigating, especially when keeping in mind I am far from the only inexperienced developer looking to include chess.js on their project.

**Comment by zekicaneksi** [comment]
I HAVE NODEJS VERSION 16 AND I'M STILL FAILING TO IMPORT THIS LIBRARY.
type module thing trick makes nodejs give errors on require's.
