### ISSUE TITLE
load_pgn returns false for most pgns even with sloppy set to true

### ISSUE THREAD

**Issue by AniruddhaGohad** [jhlywa/chess.js#326]
I am using chess.js (v0.13.1) in a react based project

usage:

```
import { Chess } from 'chess.js';

const chess = Chess();

chess.load_pgn(`
    [Event "Black to move, find the capture."]
    [Site "?"]
    [Date "?"]
    [Round "?"]
    [White "?"]
    [Black "?"]
    [Result "*"]
    [FEN "4r1k1/5p1p/4n1p1/6B1/4P3/3R3P/5PK1/8 b - - 0 1"]
    [Source "Analyze This"]
    
    1... Nxg5  *
`, { sloppy : true })
--> false
```

![image](https://user-images.githubusercontent.com/30015491/165776909-d1a522ac-6cb5-4061-a4fe-62e386f71766.png)

other pgn viewers on the internet are able to work with the same pgn:
![image](https://user-images.githubusercontent.com/30015491/165777298-e9d92b7a-810e-46d3-b8e2-34173ac614b9.png)

any idea how to resolve this?

**Comment by jhlywa** [comment]
Thanks for the report @AniruddhaGohad.  I just added some new code to strip extraneous whitespace from PGN headers which should help with this specific example.  I also extended the sloppy parser accept a FEN header tag without requiring  the usual `[SetUp "1"]` header tag.  

Please grab the latest (0.13.2) from npm to see if it fixes your issues.

```js
const chess = Chess()

const result = chess.load_pgn(
  `
    [Event "Black to move, find the capture."]
    [Site "?"]
    [Date "?"]
    [Round "?"]
    [White "?"]
    [Black "?"]
    [Result "*"]
    [FEN "4r1k1/5p1p/4n1p1/6B1/4P3/3R3P/5PK1/8 b - - 0 1"]
    [Source "Analyze This"]
    
    1... Nxg5  *
`,
  { sloppy: true }
)

console.log(result)
// -> true
```
