### ISSUE TITLE
Accessing values of empty squares

### ISSUE THREAD

**Issue by 933459** [jhlywa/chess.js#331]
Thanks for making this library, it has helped a lot in my exploratory projects. I'm a bit noob so apologize if this is an elementary question...I am not sure if this is actually a feature request or not.

Currently calling chess.board() returns an array of arrays, populated with only occupied squares. Is it possible to get the empty squares listed in this array as well, or access their square names (e.g "a3") somehow?

Use case: I am working on a 3d chess game, and representing all squares in this array makes it much easier to move a piece onto it, as the square always exists in the 3d world. But its corresponding chess.js square is sometimes null.

The board function seems to be at https://github.com/jhlywa/chess.js/blob/master/chess.js#L1428 but I can't quite work out how to make sure they always get populated. 

Any help is appreciated, thanks.

**Comment by jhlywa** [comment]
This is a little cludgy, but this should do what you need.  I'll probably change the API in the next version to include all squares in the output of `.board()`. 

```js
import { Chess, SQUARES } from './chess.js'

const chess = Chess()

for (let square = 0; square < SQUARES.length; square++) {
  const rank = Math.floor(square / 8)
  const file = square % 8

  console.log(SQUARES[square], chess.board()[rank][file])
}
```

**Comment by jhlywa** [comment]
Or even simplier:
```js
import { Chess, SQUARES } from './chess.js'

const chess = Chess()

const pieces = chess.board().flat()
for (let square = 0; square < SQUARES.length; square++) {
  console.log(SQUARES[square], pieces[square]
}
```

**Comment by 933459** [comment]
thanks @jhlywa this got me moving in the right direction
