### ISSUE TITLE
Understanding code vectors

### ISSUE THREAD

**Issue by ticaboo** [jhlywa/chess.js#334]
Hi,

Could you give us some pointers/links to understanding the underlying data structures please?
I believe they are optimisations (which by definition sacrifice human understandability). 
I found this https://www.chessprogramming.org/0x88 but a clearer explanation/links to what furthers learning would be, well - just awesome!

Hope you can help (us all!).

H

**Comment by jhlywa** [comment]
Hi @ticaboo. Here's my answer to a similar question from a few years ago: https://github.com/jhlywa/chess.js/issues/230#issuecomment-599075007. Let me know if that helps or if you still have additional questions.
