### ISSUE TITLE
Code example for integrating engine output

### ISSUE THREAD

**Issue by v11580** [jhlywa/chess.js#338]
One example  ( function and syntax)  that could be added to the github page is how to to integrate  the output of a UCI engine so that it is converted to san format.  If anyone has an example, please share.

**Comment by tennis-aa** [comment]
The following has worked for me:
```
import { Chess } from 'chess.js'
const chess = new Chess();

function EngineToSan(x) {
    let move = chess.move({ from: x.slice(0,2), to: x.slice(2,4), promotion: x.length == 5 ? x.slice(4) : "" });
    if (move) {
        chess.undo();
        return move.san;
    }
    return null;
}

let engineOutput = 'e2e4';
let san = EngineToSan(engineOutput);
```

**Comment by v11580** [comment]
Thanks for responding. Your code may work for individual moves, such as the "bestmove" for the board position. But I think to interpret an engine's pv string, we need a "for loop" that 1) takes in each move and 2) processes the fen changes after each move in the pv string.  The pv strings are mini games where the board fen is the starting position. This is my understanding of  the problem we are trying to solve.

**Comment by tennis-aa** [comment]
The stockfish example (https://github.com/nmrugg/stockfish.js/blob/master/example/enginegame.js) uses this library and I have used that as a reference. I have used the following code to parse stockfish output:
```
import { Chess } from './chess.js';
const chess = new Chess();

function pvToSan(pv) {
  let moves = pv.split(" ");
  let movesmade = 0;
  let sanvariation = [];
  for (let i=0; i<moves.length; ++i) {
    let move = chess.move({ from: moves[i].slice(0,2), to: moves[i].slice(2,4), promotion: moves[i].length == 5 ? moves[i].slice(4) : "" });
    if (move == null) break;
    ++movesmade;
    sanvariation.push(move.san);
  }
  for (let i=0; i<movesmade; ++i) {
    chess.undo();
  }
  return sanvariation;
}

const engine = new Worker("stockfish.js");
engine.postMessage("position fen " + chess.fen());
engine.postMessage("go depth 20");
engine.onmessage = function(event) {
  let line = event.data;
  let match = line.match(/^info .*\bdepth ([0-9]+) .*\bmultipv (.+) .*\bscore (\w+) (-?\d+) .*\bpv (.+)/);
  if (match) {
    let depth = parseInt(match[1]);
    let multipv = parseInt(match[2]) - 1;
    let scoreunit = match[3];
    let score = parseInt(match[4]);
    let pv = match[5];
    let sanvariation = pvToSan(pv);
    console.log(line);
    console.log(sanvariation.join(" "));
  }
}
```
The `Chess` object keeps track of the board position when you make a move, so there is no need to process the fen changes after each move. However, you need to undo all the moves after parsing to revert to the current position. 

I would say this is too specific to be added to the documentation because integrating engines is not a simple task. Maybe a link to the stockfish example could be useful.

**Comment by v11580** [comment]
Thank you for your time and patience.  I was able to integrate your code into my project!

**Comment by v11580** [comment]
Special thanks to https://github.com/tennis-aa for drafting the solution

```
function pvToSan(pv) {
  let moves = pv;
  let movesmade = 0;
  let sanvariation = [];
  for (let i=0; i<moves.length; ++i) {
    let move = game.move({ from: moves[i].slice(0,2), to: moves[i].slice(2,4), promotion: moves[i].length == 5 ? moves[i].slice(4) : "" });
    if (move == null) break;
    ++movesmade;
    sanvariation.push(move.san);
  }
  for (let i=0; i<movesmade; ++i) {
    game.undo();
  }
  
san = sanvariation.join(' ');
console.log(san)
}
```
