### ISSUE TITLE
Comments missed if black is to move

### ISSUE THREAD

**Issue by Sanketikaran** [jhlywa/chess.js#340]
The comment after a black move is missed under the pgn function.

Example PGN:

`[Event "Alma-Ata m1"]
[Site "Alma-Ata"]
[Date "1995.??.??"]
[Round "?"]
[White "Salov, Valery"]
[Black "Karpov, Anatoly"]
[Result "0-1"]
[WhiteElo "2715"]
[BlackElo "2765"]
[EventDate "1995.??.??"]
[FEN "r4rk1/p1nq1pp1/1p1pp2p/8/P2PR3/1QP2N2/1P3PPP/R5K1 b - - 0 16"]
[SetUp "1"]
[PlyCount "17"]
[Annotator "Aagaard, Jacob"]
[EventCountry "KAZ"]
[EventRounds "8"]
[EventType "blitz"]
[Source "www.chess.co.uk"]

{This position is of course essentially equal, but equal positions are won with good moves quite often, so it is important to play the best play for Black. Here the only reason why White should have any problems is that the b2-pawn is a bit weak, and that he has advanced the a-pawn. Was the a-pawn on a2, Black would not have a chance to make the advances he did in the game.}  16...Rfb8 $1 {The correct rook, as the a-rook needs to keep an eye on the a-pawn.}  17.Rae1 ( 17.c4 {will lead to a knight being established at d5. White might have a temporary initiative, but long term the d5-square will mean that the position is a bit more pleasant for Black.}  17...a6 $1 {On the next move comes 18...b5!, and although the position is not terribly frightening for White, it is certainly not entirely equal.}  ( 17...d5 $6 {would be risky. White suddenly have three pieces attacking on the kingside. After}  18.Ne5 Qe8 19.Rg4 $1 {Black has to play non-script moves such as}  19...f6 $5 {, when the position is simply unclear.}  )  )  ( 17.Ne1 $1 {as suggested by Andrew Greet was probably the most prudent move. White manouevres the knight to d3 in order to keep his all his pieces covered. In this case White probably holds equality without too much trouble.}  )  17...b5 18.axb5 Rxb5 19.Qa2 a5 $15 20.R4e2 Qc6 21.Qa4 Qb7 22.Qc4 Nd5 23.Qa2 Nf4 24.Rd2 {Black won this blitz-game on move 40, but at this point he overlooked the chance to win the game instantly with either 24...Rg5 or}  24...Nxg2 $1 0-1`

Output:

`[Event "Alma-Ata m1"]
[Site "Alma-Ata"]
[Date "1995.??.??"]
[Round "?"]
[White "Salov, Valery"]
[Black "Karpov, Anatoly"]
[Result "0-1"]
[WhiteElo "2715"]
[BlackElo "2765"]
[EventDate "1995.??.??"]
[FEN "r4rk1/p1nq1pp1/1p1pp2p/8/P2PR3/1QP2N2/1P3PPP/R5K1 b - - 0 16"]
[SetUp "1"]
[PlyCount "17"]
[Annotator "Aagaard, Jacob"]
[EventCountry "KAZ"]
[EventRounds "8"]
[EventType "blitz"]
[Source "www.chess.co.uk"]

16. ... Rfb8 {The correct rook, as the a-rook needs to keep an eye on the a-pawn.} 17. Rae1 b5 18. axb5 Rxb5 19. Qa2 a5 20. R4e2 Qc6 21. Qa4 Qb7 22. Qc4 Nd5 23. Qa2 Nf4 24. Rd2 {Black won this blitz-game on move 40, but at this point he overlooked the chance to win the game instantly with either 24...Rg5 or} Nxg2 0-1`

The comment is stored successfully in get_comments function however.

Also, are you aware that any NAG (Numeric Annotation Glyphs) in the PGN is omitted?

**Comment by jhlywa** [comment]
Thanks for the report @Sanketikaran.  This has been fixed in 0.13.4.

NAG outside of comments is currently not supported.
