### ISSUE TITLE
Get all moves for a given type of piece, at given square.

### ISSUE THREAD

**Issue by bend-n** [jhlywa/chess.js#342]
Example:
```js
console.log(chess.piece_moves({
 square: "e2", 
 color: "w", 
 piece: PAWN,
 // verbose: true,

}))
// -> [e3, e4, exf3, exd3]
```

**Comment by jhlywa** [comment]
Hi @bend-n  and thanks for the suggestion.  You can do with existing code via  `chess.moves({ square: 'e2', piece: 'p' })`.  I've updated the documentation to make this a bit clearer.

**Comment by bend-n** [comment]
@jhlywa I think you misunderstand me. `chess.moves({ square: 'e2', piece: 'p' })` will ***not*** return `[exf3, exd3]`. it will just return `[e3, e4]`, if there are no pieces at `f3`/`d3`. I want it to return `exf3` REGARDLESS of there being a piece on f3.

**Comment by bend-n** [comment]
Can you reopen this.
