### ISSUE TITLE
Move with promotion fails on the typescript (dev) branch

### ISSUE THREAD

**Issue by rafalou38** [jhlywa/chess.js#344]
I want to set the promotion to "q" as a default but when I run this code on a move not resulting in a promotion
```ts
this.chessInstance.move({
  from: ...,
  to: ...,
  promotion: "q",
});
```
It works on the master branch but not on the dev branch,
Is it made on purpose ?

I used the debugger and noticed that the issue comes from here (move function):
```ts
(!('promotion' in moves[i]) || move.promotion === moves[i].promotion)) {
```

in the master branch, `moves[i].promotion` does not exist
in the dev branch   , `moves[i].promotion` is undefined

**Comment by jhlywa** [comment]
Thanks for the report @rafalou38.  I'm trying to understand this issue more clearly.  Are you providing `{ promotion: 'q' }` even when the move is not a promotion?

**Comment by rafalou38** [comment]
Yes, for all the moves.

**Comment by jhlywa** [comment]
This should be fixed on the `dev` branch.
