### ISSUE TITLE
Request for 1.0.0 alpha release

### ISSUE THREAD

**Issue by LandonSchropp** [jhlywa/chess.js#346]
Hello! I've been using the TypeScript version of Chess.js in a side project and it's working great! Since there's not currently an NPM release for this project yet, I've connected NPM to the dev branch and I've been importing Chess.js directly like this:

```
import { Chess } from "chess.js/src/chess";
```

Recently, I decided to try and turn on the `noUncheckedIndexedAccess` to catch some bugs in my code, but now I'm no longer able to compile the Chess.js build.

If you could build and release an alpha version of the refactor, then I'd be able to use that build instead.

Thanks for creating such a great library!

**Comment by jhlywa** [comment]
Hi @LandonSchropp.  Sorry for the radio silence - summer has been very busy.

I've pushed up an alpha release 1.0.0-alpha.0 to npm.  Please let me know if it work for you.

**Comment by LandonSchropp** [comment]
Hi @jhlywa! Sorry for the slowness on my end—I missed your last message.

The build you pushed up works great. Thank you!
