### ISSUE TITLE
Empty board with valid FEN string?

### ISSUE THREAD

**Issue by Xwilarg** [jhlywa/chess.js#351]
Hey,

I have a fen string that looks like that: 8/8/4r3/7r/8/8/4r3/8
And I instanciate (and display) my board this way:
```
const chess = new Chess(fen);
console.log(chess.ascii());
```

When I check online the FEN looks valid: http://www.ee.unb.ca/cgi-bin/tervo/fen.pl?select=8%2F8%2F4r3%2F7r%2F8%2F8%2F4r3%2F8

However when I display the board it's empty:
```
   +------------------------+
 8 | .  .  .  .  .  .  .  . |
 7 | .  .  .  .  .  .  .  . |
 6 | .  .  .  .  .  .  .  . |
 5 | .  .  .  .  .  .  .  . |
 4 | .  .  .  .  .  .  .  . |
 3 | .  .  .  .  .  .  .  . |
 2 | .  .  .  .  .  .  .  . |
 1 | .  .  .  .  .  .  .  . |
   +------------------------+
     a  b  c  d  e  f  g  h
```

I tried to use chess.validate_fen but it gives me the following error:
```
Uncaught TypeError: chess.validate_fen is not a function
```

**Comment by Xwilarg** [comment]
After considering my code a bit more, I guess this library doesn't exactly fit my needs so I'm closing this issue

**Comment by ajax333221** [comment]
maybe you needed to add the other fen info, example `...  w KQkq - 0 1`

**Comment by tissatussa** [comment]
i did not work with chess.js but i see your FEN does not have Kings : it's an invalid position !

**Comment by Xwilarg** [comment]
Yup I wanted to create a custom board to make another game that is played with chess pieces but not the same way
