### ISSUE TITLE
A promotion + capture of a pawn incorrect flag

### ISSUE THREAD

**Issue by gerardpp** [jhlywa/chess.js#356]
In the documentation, where it says:

"A flags value of pc would mean that a pawn captured a piece on the 8th rank and promoted."

It should be 'cp', not 'pc'.

**Comment by jhlywa** [comment]
Hi @gerardpp.  It's not clear in the documentation, but the order should be ignored.  So use something like `move.flags.includes('p')` to check to see if the move is a promotion.  I'll add helper function to abstract this away in the future.

**Comment by gerardpp** [comment]
Noted. Thanks!
