### ISSUE TITLE
inCheckmate on the ReadMe should be isCheckmate

### ISSUE THREAD

**Issue by jffy0220** [jhlywa/chess.js#357]
`inCheck(): boolean;
isCheckmate(): boolean;`

On lines 68 & 69 of the chess.d.ts file, while the ReadMe has 'InCheckmate'

**Comment by gerardpp** [comment]
I can confirm the issue. As @jffy0220 stated, the right function should be isCheckmate().
Please correct the documentation.

**Comment by jhlywa** [comment]
Thanks and fixed
