### ISSUE TITLE
move function doesn't run 2nd time (in typescript)

### ISSUE THREAD

**Issue by aniq-makrani** [jhlywa/chess.js#361]
Hello,
I am trying to run move function in a for-loop, its working fine during 1st loop but whenever i update my state it stops working, i am getting 'null' value. 

let tempLiveGameMoves = liveGameData.ms;
for (var i = 0; i < tempLiveGameMoves.length; i++) {
          let game_movement = game.move(tempLiveGameMoves[i].move, {sloppy:true});
          console.log(game_movement);
}

i am new to typescript so can you pls me with this ? am i missing something ?

**Comment by jhlywa** [comment]
Hi @aniq-makrani.  Are you calling `chess.reset()` in between loops?  If not, the moves you're attempting (during the second loop) are illegal in the current board position.

**Comment by aniq-makrani** [comment]
Hi @jhlywa, i was using chess.reset() before my loop that's why it was not working, as you said i shifted it after my loop so its working now, thank you very much for your help :)
