### ISSUE TITLE
loadPgn doesn't work on a pgn without any moves yet

### ISSUE THREAD

**Issue by kevo1ution** [jhlywa/chess.js#362]
**What**
`chess.loadPgn` doesn't work on a pgn that has no moves yet.

```js
const { Chess } = require('chess.js')

const game = new Chess();
game.header('White', 'id0');
game.header('Black', 'id1');
// game.move('e4'); // uncomment this for loadPgn to work

console.log(game.pgn())
/** output:
[White "id0"]
[Black "id1"]

*/

console.log('trying to load into another game instance')

const gameCpy = new Chess();
const result = gameCpy.loadPgn(game.pgn())
console.log('result:', result) // output: false
```

**Why**
It would be nice to rely solely on the pgn to describe the game, especially when saving the string in a database to track the game to be loaded for future play/moves.

**Comment by jhlywa** [comment]
Hi @kevo1ution. I just confirmed this. I agree, this is something that should be supported.

**Comment by kevo1ution** [comment]
@jhlywa awesome! I can take a stab at it if that is okay
