### ISSUE TITLE
Comment at the beginning of pgn breaks parsing

### ISSUE THREAD

**Issue by JocaPC** [jhlywa/chess.js#364]
`load_pgn()` cannot load a pgn if a comment is added before the first move:

```
5/PP3PPP/R1BQKB1R b KQkq - 0 4"]
[SetUp "1"]

{ Remove this comment to make it working }
1... Bb4
2. Bd2 Nc6
3. Nxc6 *`;


var game = new Chess();
game.load_pgn(pgn);
document.writeln(game.history().length)
```

Once I remove the comment `load_pgn()` will load the pgn.

**Comment by jhlywa** [comment]
Hi @JocaPC.  Your PGN looks like it was truncated.  Can you please repost?

**Comment by JocaPC** [comment]
Hi @jhlywa, 

Could you open this jsbin: https://jsbin.com/saxolam/3/edit?html,js,output and you will see the output:

```
rnb1kb1r/1pqp1ppp/p3pn2/8/2PNP3/2N5/PP3PPP/R1BQKB1R b KQkq - 0 4
0
```
This one without comment works fine: https://jsbin.com/saxolam/4/edit?html,js,output
```
r1b1k2r/1pq2ppp/p1p1pn2/8/1bP1P3/2N5/PP1B1PPP/R2QKB1R w KQkq - 0 7
5
```
Note that I'm using v 0.10.2: 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/chess.js/0.10.2/chess.js" integrity="sha384-s3XgLpvmHyscVpijnseAmye819Ee3yaGa8NxstkJVyA6nuDFjt59u1QvuEl/mecz" crossorigin="anonymous"></script>
```

Do you have URI of the latest stable version that I can try to put in the repro?
