### ISSUE TITLE
is_checkmate() == false

### ISSUE THREAD

**Issue by sowson** [jhlywa/chess.js#365]
thanks for the awesome library, can you help? situation below...

![Screenshot 2022-12-24 at 14 52 04](https://user-images.githubusercontent.com/33941184/209438886-0eb2dabb-177c-4c67-a728-51cd08667979.png)

**Comment by jhlywa** [comment]
Hi @sowson.  I can't reproduce here.  If you're loading the position from FEN, double-check that you have set the appropriate side to move.

```js
import { Chess } from "chess.js";

// load position from FEN
const chess = new Chess(
  "rnb1kbnr/pppp1ppp/4p3/8/6Pq/5P2/PPPPP2P/RNBQKBNR w KQkq - 1 3"
);
console.log(chess.isCheckmate());
// -> true

// play moves from starting position
chess.reset();
chess.move("f3");
chess.move("e5");
chess.move("g4");
chess.move("Qh4#");
console.log(chess.isCheckmate());
// -> true
```

**Comment by jhlywa** [comment]
Hi @sowson.  I can't reproduce here.  If you're loading the position from FEN, double-check that you have set the appropriate side to move.

```js
import { Chess } from "chess.js";

// load position from FEN
const chess = new Chess(
  "rnb1kbnr/pppp1ppp/4p3/8/6Pq/5P2/PPPPP2P/RNBQKBNR w KQkq - 1 3"
);
console.log(chess.isCheckmate());
// -> true

// play moves from starting position
chess.reset();
chess.move("f3");
chess.move("e5");
chess.move("g4");
chess.move("Qh4#");
console.log(chess.isCheckmate());
// -> true
```

**Comment by sowson** [comment]
Thanks! I miss the middle else that needs to be if else in the code below (chess is game and moveColor is color):
if (game.in_checkmate()) {
        status = 'Game over, ' + moveColor + ' is in checkmate.'
}
else if (game.game_over() || game.in_threefold_repetition() || game.in_draw()) {
    status = 'Game over, drawn position'
}
else {
    status = moveColor + ' to move'
    if (game.in_check()) {
        status += ', ' + moveColor + ' is in check'
    }
}

Thank you, we may close the issue!
