### ISSUE TITLE
Generate legal moves is too slow 

### ISSUE THREAD

**Issue by TheDarkKnightRise** [jhlywa/chess.js#368]
Hi Jeff , I want to use your JavaScript library for my chess engine 

```
    /* filter out illegal moves */
    var legal_moves = []
    for (var i = 0, len = moves.length; i < len; i++) {
      make_move(moves[i])
      if (!king_attacked(us)) {
        legal_moves.push(moves[i])
      }
      undo_move()
    }
```

but this is too slow because needed `make_move` & `undo_move` for checking legality

How can get legal moves without make move ?

**Comment by jhlywa** [comment]
Hello @TheDarkKnightRise. Don't use legal move generation in the search function of your engine. Generate all psuedo-legal moves first, then filter out the illegal ones at the next search depth.  See the internal `perft` function for an example for this.  I may need to expose an `isAttacked` function in the API to help with this approach.

Just a reminder that any JS-based engine will be relatively slow.  The performant web-based engines all use C and WASM.

**Comment by TheDarkKnightRise** [comment]
I need to have legal moves number before loop  ,please compare this two `perft` function speed

_**Time (ms) : 10053
Nodes  : 120921506
NPS  : 12000**_

```
  function perft(depth) {
    var moves = generate_moves({ legal: false })
    var nodes = 0
    var color = turn
	
    if(depth == 1) {  return moves.length }

    for (var i = 0, len = moves.length; i < len; i++) {
      make_move(moves[i])  
         var child_nodes = perft(depth - 1)
         nodes += child_nodes
      undo_move()
    }

    return nodes
  }
```
---

_**Time (ms) : 30481
Nodes  : 120921506
NPS  : 4000**_

```
  function perft(depth) {
    var moves = generate_moves({ legal: false })
    var nodes = 0
    var color = turn

    for (var i = 0, len = moves.length; i < len; i++) {
      make_move(moves[i])
        if (depth - 1 > 0) {
          var child_nodes = perft(depth - 1)
          nodes += child_nodes
        } else {
          nodes++
        }
      undo_move()
    }

    return nodes
  }
```

### we can calculate perft 3x faster if we have legal number before loop

**Comment by jhlywa** [comment]
The goal of `.perft()` is two-fold. First, it's used to ensure the accuracy of the move generator by determining node counts from well known [perft positions](https://www.chessprogramming.org/Perft_Results).  Second, it's used to measure the performance of the move generator as well as the `.move()` and `.undo()` functions.  Feel free to make perft faster, but please don't change the perft logic to do so.

**Comment by jhlywa** [comment]
I added an [isAttacked](https://github.com/jhlywa/chess.js#isattackedsquare-color) function that may be helpful to you.

**Comment by TheDarkKnightRise** [comment]
Thank you very much , Now How can generate legal moves without  `.move()` and `.undo()` ?

Please send a Code samples to generate legal moves with `isAttacked` function

**Comment by jhlywa** [comment]
You cannot generate legal moves without calling `.move()` and `.undo()` at some point.  You can, however, limit the number of calls to those function by using `isAttacked`.  I'm assuming you're writing a JS chess engine, so you'd be similar logic below:

#### Slow (legal moves only - 2n calls to move/undo)
```js
function slow_search(chess, depth) {
  
  if (depth == 0) return evaluate_position(chess)

  let score = 0
  const moves = chess.moves() // calls move/undo for every potential move to ensure legality

  for (let move in moves) {
    chess.move(move) // <- another call to move/undo
    score = slow_search(chess, depth - 1)
    chess.undo()
    // compare scores and store highest (omitted here for brevity)
  } 

  return score
}
```

#### Faster (pseudo-legal moves - n calls to move/undo)
```js
function faster_search(chess, depth) {
 
  if (depth == 0) return evaluate_position(chess)

  let score = 0
  const moves = chess.moves({ legal: false }) // NO calls move/undo in here
  const color = chess.turn()
  
  for (let move in moves) {
    chess.move(move) // <- one call to move/undo
    
    // make sure the move we just made didn't place ourselves in check
    // you need to store and track kingPosition
    if (!chess.isAttacked(kingPositions[color], color)) {   
      score = faster_search(chess, depth - 1)
    }

    chess.undo()
    // compare scores and store highest (omitted here for brevity)
  } 

  return score
}
```

Does that help?

**Comment by TheDarkKnightRise** [comment]
I tested `isAttacked`in `perft` function but  just a bit faster (100ms) 

I don't know generating legal moves without calling `.move()` and `.undo()`  is faster or slower  ?!

but i found a js library that can generate legal moves without `.move()`  and  `.undo()`

```js
Board.prototype.generateMovesFrom = function (square) {
    var us = this.sideToMove;
    var piece = this.board[square];

    if (pieceColor(piece) != us) {
        return [];
    } else if (pieceType(piece) == PAWN) {
        return this.generatePawnMovesFrom(square);
    } else if (pieceType(piece) == KNIGHT) {
        return this.generateKnightMovesFrom(square);
    } else if (pieceType(piece) == BISHOP) {
        return this.generateBishopMovesFrom(square);
    } else if (pieceType(piece) == ROOK) {
        return this.generateRookMovesFrom(square);
    } else if (pieceType(piece) == QUEEN) {
        return this.generateQueenMovesFrom(square);
    } else {
        return this.generateKingMovesFrom(square);
    }
};

Board.prototype.generateEvasionsFrom = function (square) {
    var us = this.sideToMove;
    var piece = this.board[square];

    if (pieceColor(piece) != us) {
        return [];
    } else if (pieceType(piece) == PAWN) {
        return this.generatePawnEvasionsFrom(square);
    } else if (pieceType(piece) == KNIGHT) {
        return this.generateKnightEvasionsFrom(square);
    } else if (pieceType(piece) == BISHOP) {
        return this.generateBishopEvasionsFrom(square);
    } else if (pieceType(piece) == ROOK) {
        return this.generateRookEvasionsFrom(square);
    } else if (pieceType(piece) == QUEEN) {
        return this.generateQueenEvasionsFrom(square);
    } else {
        return this.generateKingEvasionsFrom(square);
    }
};

Board.prototype.movesFrom = function (square) {
    if (this.isCheck()) {
        return this.generateEvasionsFrom(square);
    } else {
        return this.generateMovesFrom(square);
    }
};

```
It generate moves with `EVASIONS` & `NONEVASIONS ` moves

I attach whole library file here , Please see that is it possible to make legal moves without `.move()` and `.undo()` ?!

 faster or slower ?

[chess.zip](https://github.com/jhlywa/chess.js/files/10354011/chess.zip)

**Comment by jhlywa** [comment]
I don't have time to dig into the internals of that library, but I suspect you'll find the author is doing a lot of bookkeeping in the move/undo function to keep track of whether or not current side to move is in check. At the end of the day, this type of change would slow down many API calls (`move`, `undo`, `load`, `put` ... the bookkeeping needs to be done in all of those places) for a slightly faster `.moves()` function only when the one side to move is in check. For a general purpose chess library, I'm not willing to make this change at this time.

If you're trying to write a chess engine (which needs to evaluate _many_ positions during the tree search), `.move()` will be called millions of times. Tweaking `perft` to artificially run faster means nothing if you're not actually reaching all nodes (positions) on the board.

I encourage you to continue development of your chess engine. It's great fun and a very rewarding exercise.

**Comment by TheDarkKnightRise** [comment]
Thank you very much , I try to combine 2 chess library for create new branch But I am not sure if this is possible !

I think your library is fastest library  but it not possible to create artificially `perft`
