### ISSUE TITLE
[Bug] Permissive Parser failing on certain type of non-standard captures

### ISSUE THREAD

**Issue by ChrisAntley1** [jhlywa/chess.js#375]
Using chess.js 1.0.0-beta.2

Noticed a small bug in the permissive parser for non-standard moves that result in a capture. Happens when the move doesn't indicate itself as a capture (no 'x'):

```
// with pieces:
const Chess = require('chess.js');

const chess = new Chess.Chess("r1bqk2r/p1p2pp1/2n1pn2/1p5p/2pP4/bPNB1PN1/PB1Q2PP/R3K2R w KQkq - 0 12");

console.log(chess.ascii());
console.log(chess.moves({square: 'b2'}));
console.log(chess.move('Ba3', { strict: false }));
```

![image](https://user-images.githubusercontent.com/77400072/216442112-a30b763f-223c-4069-8c3e-5740bfc2ca59.png)
```
// with pawns:
const Chess = require('chess.js');

const chess = new Chess.Chess("r1bqk2r/p1p2pp1/2n1pn2/1p5p/2pP4/bPNB1PN1/PB1Q2PP/R3K2R w KQkq - 0 12");

console.log(chess.ascii());
console.log(chess.moves({square: 'b3'}));
console.log(chess.move('bc4', { strict: false }));
```

![image](https://user-images.githubusercontent.com/77400072/216442264-34fb6a34-2cab-4844-aad9-03df1f12eb88.png)

Expected this to work based off the list of moves that permissive parser should interpret correctly:

![image](https://user-images.githubusercontent.com/77400072/216443450-feadb9bb-2fd9-4e30-8ad2-1b9c41ba9955.png)

Thanks to everyone who contributes to this library!

**Comment by jhlywa** [comment]
Thanks for the report @ChrisAntley1. I may have gotten overzealous writing the documentation.  I'll look into fixing this, but if it's not critical, I may defer this until after the 1.0.0 release.
