### ISSUE TITLE
Skip the move

### ISSUE THREAD

**Issue by KH93b** [jhlywa/chess.js#382]
Hello. Help, I have not a standard situation. I want that under certain conditions the opponent could skip the move and pass it to the opponent. how to do it?

**Comment by jhlywa** [comment]
How about this (untested) snippet:
 
```js
let tokens = chess.fen().split(/\s/)
tokens[1] = chess.turn() == chess.WHITE ? chess.BLACK : chess.WHITE
tokens[3] = '-' // reset the en passant square 
chess.load(tokens.join(' '))
```

Keep in mind that this code will destroy your move history. It'll also let you capture the king if the side doing the skipping is in check.

**Comment by KH93b** [comment]
> It'll also let you capture the king if the side doing the skipping is in check.

is there a solution to this problem?

**Comment by KH93b** [comment]
Or maybe there is a way to change the source code that does not change the tokens?

**Comment by jhlywa** [comment]
There's no solution to king capture at this time ... and I'm not sure they'll ever be one. You could always prevent skipping moves if the side to move is in check (e.g. wrap the block above in `if (!chess.inCheck()) { ... }`
