### ISSUE TITLE
Custom Piece Moves

### ISSUE THREAD

**Issue by Pain2821** [jhlywa/chess.js#383]
I want to customize chess pieces moves I tried by inheritance but its not working as it should be can anyone give some ideas how to do it like I want knight, bishop and rook to move as king as well and pawn to capture one square head...?

**Comment by jhlywa** [comment]
It's not trivial to add new pieces types due to the optimized internal algorithm. It can be done, but you'll have to change a fair amount of code. See https://github.com/jhlywa/chess.js/issues/230#issuecomment-599075007 for more info about move/attack generation in chess.js
