### ISSUE TITLE
Freeze board?

### ISSUE THREAD

**Issue by thewebsitedev** [jhlywa/chess.js#396]
Hello, is there a way to freeze the board after a certain number of moves? I tried returning false for `onPieceDragBegin`, but it does not work. And I get an error `onPieceDragBegin is not a function. (In 'onPieceDragBegin(piece, square)', 'onPieceDragBegin' is false)`. I don't want a user to be able to make any more moves.

I am using the latest stable version.

Thank you.

**Comment by neofight78** [comment]
This project is chess.js and only takes care of the chess logic and not the interface. Probably you need to raise your issue for the chessboard.js project that implements an actual user interface.
