### ISSUE TITLE
Invalid move

### ISSUE THREAD

**Issue by namelessChessfoot** [jhlywa/chess.js#401]
Hi Jeff, I am using chess.js and it works fine on my laptop but if I deploy my project to Netlify, something strange happened.

The problem is that on Netlify, chess.move("e4") results in "invalid move: e4". I added some logs and found that chess.isGameOver() returns false on my laptop but true on Netlify.

With more tests, I found that the chess on Netlify always returns true for isGameOver(). Even if I run chess.load('2k5/4P3/4K3/8/8/8/8/8 b - - 0 78'), it says the game is over. The output is correct on my laptop.

Both of them are running the same code. I am a little confused. Do you have any suggestions?

Thanks

**Comment by jhlywa** [comment]
Thanks for the report @namelessChessfoot. This is indeed a strange one.  Let's start by unrolling `isGameOver()` to see what's triggering the end of game condition. Can you print the following when running on production:

```js
chess.load('2k5/4P3/4K3/8/8/8/8/8 b - - 0 78')
console.log('fen', chess.fen())
console.log('isCheckmate', chess.isCheckmate())
console.log('isStalemate', chess.isStalemate())
console.log('isInsufficientMaterial', chess.isInsufficientMaterial())
console.log('isThreefoldRepetition', chess.isThreefoldRepetition())
```

I'm unfamiliar with Netlify. How are you bundling your javascript (webpack, rollup, etc)?

**Comment by namelessChessfoot** [comment]
I tried to deploy my code to Render.com and now it works. It is really strange that deploying to Netlify does not work. If you are busy, feel free to close this issue.

Regarding the extra tests on Netlify, everything is correct except for `isStalemate()`, which returns `true`. After reading the source code, I found that the root cause is that `chess.moves()` always returns `[]` on Netlify.

In order to debug conveniently, I created a separate page that can run JS code. Here they are:

On Render.com, [https://chess-fans.onrender.com/debug](url)
On Netlify, [https://stunning-frangollo-a69652.netlify.app/debug](url)

And this is my source code for this page, [https://github.com/namelessChessfoot/chess-fans/blob/master/src/game/debug.js](url)

I can type the following code in the text area and run it directly.
```
const chess = getChess();
chess.load('2k5/4P3/4K3/8/8/8/8/8 b - - 0 78')
console.log('fen', chess.fen())
console.log('isCheckmate', chess.isCheckmate())
console.log('isStalemate', chess.isStalemate())
console.log('isInsufficientMaterial', chess.isInsufficientMaterial())
console.log('isThreefoldRepetition', chess.isThreefoldRepetition())
```

The output will occur in the console. The outputs on the two platforms are different.

Regarding bundling, I do not know it too much. I use `npm run build` to build my project, which is actually `react-scripts build`. ChatGPT says this command uses Webpack.

Anyway, now I can continue with my homework. Thanks for your chess.js which helps me a lot. If you are interested in figuring out the root cause, I would also do it with you.
