### ISSUE TITLE
game.IsAttacked is not a function

### ISSUE THREAD

**Issue by SeanTalley** [jhlywa/chess.js#422]
Am I missing something here? The API seems to suggest that there is an `isAttacked` function, but despite upgrading the library to the latest beta, I continue to receive this error.

Any chance you guys could help me out with this? I'm sure I'm doing something wrong.

**Comment by jhlywa** [comment]
Hi @SeanTalley. Perhaps you're running with an older version?  I suggest a fresh install from npm: `npm i chess.js`

**Comment by SeanTalley** [comment]
Hey @jhlywa, I appreciate your quick reply. I don't know what exactly was going on before, but now all the new functions are there. Definitely something I did. Great library by the way and thanks for your help!
