### ISSUE TITLE
get() method of Chess class returns false instead null

### ISSUE THREAD

**Issue by GienKu** [jhlywa/chess.js#427]
Hello, I'm a beginner programmer, and I have encountered a problem as described in the title. I have also checked the implementation, which is as follows:
`  get(square: Square) {
    return this._board[Ox88[square]] || false
  }
  `
 Should it be like this? 
 `console.log(game.get('a6')); // prints false`

**Comment by jhlywa** [comment]
Hi @GienKu. Welcome to programming and thanks for the report!

It looks like you found a typo in the code that has been there for over a year. Looking at it with fresh eyes (and with TypeScript) in mind, it may be more idiomatic for `get` to return a `Piece | undefined`. I'm going to leave this open for a few days while I decide on what to do.

Thanks!

**Comment by michelsafi** [comment]
hello. any update on this issue

**Comment by datacurse** [comment]
greetings! any chance of this being implemented? 

> Hi @GienKu. Welcome to programming and thanks for the report!
> 
> It looks like you found a typo in the code that has been there for over a year. Looking at it with fresh eyes (and with TypeScript) in mind, it may be more idiomatic for `get` to return a `Piece | undefined`. I'm going to leave this open for a few days while I decide on what to do.
> 
> Thanks!

**Comment by jhlywa** [comment]
Fixed in commit [85c049e](https://github.com/jhlywa/chess.js/commit/85c049eacab7312844af8ff619eb02e3bcfee7f0)
