### ISSUE TITLE
isAttacked is not working

### ISSUE THREAD

**Issue by sairamnst** [jhlywa/chess.js#439]
i even tried implementing the fen given in the docs of isAttacked function....still its giving false for any value given....

**Comment by jhlywa** [comment]
Thanks for the report @sairamnst. While all of the `isAttacked` tests are passing, none of the examples in the documentation appear to be working. I'm looking into this now.

**Comment by jhlywa** [comment]
It was a typo in docs.  The chess.js constants (`WHITE`, `BLACK`, `DEFAULT_POSITION`) aren't exported in the `Chess` class, they're exported from the module itself. Try this:

```js
import { Chess, BLACK } from 'chess.js'

const chess = new Chess();
chess.load("4k3/4n3/8/8/8/8/4R3/4K3 w - - 0 1");
console.log(chess.isAttacked("c6", BLACK));
```

**Comment by jhlywa** [comment]
I added a blurb to the documentation about the available constants. Thanks again for the report

**Comment by sairamnst** [comment]
Thanks for the very quick help....i thought of finding the error and contributing myself but you were really quick...thx once again
