### ISSUE TITLE
Less Strict FEN Validation

### ISSUE THREAD

**Issue by LandonSchropp** [jhlywa/chess.js#442]
I'm a bit bummed that FEN parameters are now validated strictly inside of Chess.js. I think that this prevents the library from being used in a few useful use cases, such as board editors or scripts that generate positions one piece at a time.

For example, in my current project, I'm generating endgame positions that the player can practice against the computer. Each piece is placed on the board based on a set of constraints. 

``` typescript
let availableSquares = new Set(SQUARES);
let pieceSquaresTuples = exercise.pieces.map(convertConstraintToAllowedSquares);
let chess = new Chess("8/8/8/8/8/8/8/8 w KQkq - 0 1");

for (let [piece, allowedSquares] of pieceSquaresTuples) {
  let square = randomPiece(availableSquares, allowedSquares);
  chess.put(PIECE_TO_CHESS_JS_PIECE[piece], square);
  availableSquares.delete(square);
}
```

However, this doesn't work because Chess.js doesn't allow me to load an empty position.

Instead of forcing validation, maybe the library could include an `isValid` property so a dev can choose to use it or not.

**Comment by jhlywa** [comment]
@LandonSchropp Yep, that's an oversight on my part. I'll add an optional parameter to skip the fen validate during `.load()`

**Comment by LandonSchropp** [comment]
@jhlywa Awesome! Thank you so much. 🙏

**Comment by jwwells42** [comment]
Similar use case here: working up a baby version of Lichess.org's "Learn: Chess Basics" to use where I teach, since my school can't allow Lichess.org universally (due to the potential of an eight year old registering and talking to strangers, even if we make them a kid account). When I'm showing new students on the demo board, I don't start with kings on!

For someone who last wrote any code a decade ago, it is brilliant that the hard work is already done, and I can build my little teacher's aide quickly and get going. Thank you for your effort here!

**Comment by jhlywa** [comment]
@jwwells42 Hi, and thanks for the kind words. I've got a fix for this in place, but I've gotten sidetracked updating the documentation - which has gotten pretty messing lately. If you can hang tight for a few more days, I'll have a new beta ready then.

**Comment by jhlywa** [comment]
Fixed in e2ff91c7501, included in `1.0.0-beta.7`, and pushed to NPM.

**Comment by LandonSchropp** [comment]
@jhlywa Thank you for tackling this!

I played around with the change, and it seems to work. However, the usage of `load` feels a bit awkward here.

Here's an example:

``` typescript
let chess = new Chess();
chess.load("8/8/8/8/8/8/8/8 w - b 0 1", { skipValidation: true });

chess.put({ type: "k", color: "w" }, "e1");
chess.put({ type: "k", color: "b" }, "h1");
chess.put({ type: "p", color: "b" }, "a2");
```

I still think a simpler API would be to use an `isValid` property. That way, if somebody cares if the represented position is invalid, then they can check it. Otherwise, they're not bothered.

This change would look like this:

``` typescript
let chess = new Chess("8/8/8/8/8/8/8/8 w - b 0 1");

chess.put({ type: "k", color: "w" }, "e1");
chess.put({ type: "k", color: "b" }, "h1");
chess.put({ type: "p", color: "b" }, "a2");

if (!chess.isValid) {
  throw new Error("The position is not valid.");
}
```

**Comment by jhlywa** [comment]
Ah, I see your intent.  I think you can accomplish something similar now using `validateFen`:

```js
import { Chess, validateFen } from "chess.js";

const chess = new Chess();

chess.clear();
// or chess.load(fen, { skipValidation: true })

chess.put({ type: "k", color: "w" }, "e1");
chess.put({ type: "k", color: "b" }, "h1");

const valid = validateFen(chess.fen());

if (!valid.ok) {
    throw new Error(valid.error);
}
```
I realize this isn't the most ergonomic solution. Some sort of computed property would be a nice addition (it would be nice too if we could incorporate `validateFen` error messages into the return value).

My preference is to keep the FEN validation in `.load()` enabled by default. Lots of folks botch FEN strings.

Does the snippet above solve your issue (at least in the short term)?

**Comment by LandonSchropp** [comment]
> My preference is to keep the FEN validation in .load() enabled by default. Lots of folks botch FEN strings.

That makes sense.

> Ah, I see your intent. I think you can accomplish something similar now using validateFen:

To clarify, I was only giving an example of what the API could look like. My actual use case is different (grabbing arbitrary FENs that could or could not be valid), and your original change of adding `skipValidation` solved it for me. (I didn't know about `clear` though—handy!)

I appreciate you jumping in to help. 🙂

What do you think about adding the `skipValidation` option to the constructor? Since the constructor just calls `this.load(fen)`, maybe it could pass the other options along as well?

Something like this?

```
let chess = new Chess("8/8/8/7K/8/8/8/8 w - b 0 1", { skipValidation: true });
```
