### ISSUE TITLE
I can't get possible moves for black pieces

### ISSUE THREAD

**Issue by bigg-S** [jhlywa/chess.js#449]
When I use the .moves() function from the Chess object and pass in the type, color and square, it only returns possible moves for white pieces, never the black ones. Any help will be great

**Comment by jhlywa** [comment]
The Chess object is stateful and currently does easily support switching colors without making a move. You can use this in a pinch:

```js
const side = "b";
const [position, _, castling] = chess.fen().split(" ");
const fen = `${position} ${side} ${castling} - 0 1`;
chess.load(fen);
console.log(chess.moves());
```
Keep in mind this code could allow undefined/illegal behavior (e.g. switching sides while one side is in check).

**Comment by bigg-S** [comment]
I appreciate the response. I tried it and it worked. Thank you!

**Comment by bigg-S** [comment]
I think I know the issue in my code, When I create an instance of Chess(), a board is initialized and it has the pieces set to their default positions. To correct this I have to use a single instance and update it whenever a move is made, Help me confirm if this is right. Thanks.
