### ISSUE TITLE
Game throws invalid error instead of null for invalid moves

### ISSUE THREAD

**Issue by quackquavk** [jhlywa/chess.js#472]
```
 function makeAMove(move) {
    const gameCopy = new Chess(game.fen());
    const moves = game.moves();
   
    const lastPiece = game.get(move.to);
    const lastFen = game.fen();
    const result = gameCopy.move(move);
    
```
gameCopy is throwing error saying move invalid move previously it just used to return null for invalid moves

**Comment by jhlywa** [comment]
Newer versions 1.0.0-beta.x throw exceptions for invalid moves. You'll need to lock your version to v0.13.4 if you want the previous behavior.
