### ISSUE TITLE
loadPgn throws for disambiguated knight move

### ISSUE THREAD

**Issue by jo-sip** [jhlywa/chess.js#475]
E.g moves: `1. g3 e5 2. f4 Nc6 3. Nfe3 a6 4. Nc3 Nd4 5. a3 c6 6. Ba2 Ba7 7. fxe5 f6 8. Bxg8 Qxg8 9. exf6 gxf6 10. Nf5 Nxf5 11. Qe4 Bg6 12. Rf1 Nxg3 13. Bxg3 Bxe4 14. Nxe4 Bd4 15. Nxf6 Bxf6 16. Rxf6 Ne6 17. O-O-O O-O-O 18. Rdf1 Rf8 19. c3 Rxf6 20. Rxf6 Qg5 21. Rf3 h5 22. h4 Qg4 23. b4 d5 24. a4 Qe4 25. Rf6 Qxe2 26. Rf7 b5 27. Rf8+ Nxf8 28. axb5 axb5 0-1`

Throws: `Error: Invalid move in PGN: Nfe3`.

**Comment by jhlywa** [comment]
Ne3 (or Nfe3) is not a legal move on move 3.
