### ISSUE TITLE
Free fen, Free moves

### ISSUE THREAD

**Issue by mohsenD98** [jhlywa/chess.js#476]
Hi.
is it possible to load fen like `8/1n1p3p/8/8/6B1/8/2r5/8 w - - 0 1` ? as you can see there is no king on the board, just some pieces.
it is useful in chess games, so does Chess.js supports this kinda fen ?

if yes, then can i use `chess.move({"from": "g4", "to": "f5"})` for example ? 

it returns null.

**Comment by mmaciesowicz** [comment]
There is a `load` function that allows you to setup the board and skip the validation (by setting skipValidation = true) which will allow you to use it without doing the FEN validation such as checking number of kings on the board:

`load(fen: string, { skipValidation = false, preserveHeaders = false } = {})`

**Comment by mohsenD98** [comment]
That would work..
Much appreciated 👍
