### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by bendathierrycom** [jhlywa/chess.js#49]
Hello jhlywa,

Could we have an example in your package (in "master" or in your jquery "widget") in which you can choose the piece you want to take when you are promoting a pawn.

It could be very good for people whom don't practise javascript every day.

Thanks for that tool, it is a good one :+1: 

Thierry

**Comment by L0rdH4x0r** [comment]
> `//promote to queen. Other pieces are 'r' for rook, 'k' for knight and 'b' for bishop
chess.move({ from: 'a7', to: 'a8', promotion:'q' });`

Actually its **n** for the knight! I found the bug in _enginegame.js_ on ai promote as well...

**Comment by Nikola-Obreshkov** [comment]
There should be a function `is_promotion(from, to)` in chess.js and to return true if the move is valid and is promotion move. After that this issue can be solve like this:
`
var piece_code = 'q';
if ( is_promotion(from, to) ) {
      //a modal window lets the user to choose a promotion piece
      piece_code = choose_piece();
}
chess.move({ from: from, to: to, promotion: piece_code });
`

**Comment by L0rdH4x0r** [comment]
You are absolutely right. Actually I'm doing this in a hackish way, where I check if the move exists in `chess.moves({ verbose: true });`. The dialog you mentioned should be handled with a Promise/await pattern. Unfortunately this is ES6, but webpack could compile the module down to a compatible state machine.
You are welcome to implement this feature in a separate branch, which could be merged into the master branch later on. This would definitely improve the handling for everyone.

**Comment by justingolden21** [comment]
> > `//promote to queen. Other pieces are 'r' for rook, 'k' for knight and 'b' for bishop chess.move({ from: 'a7', to: 'a8', promotion:'q' });`
> 
> Actually its **n** for the knight! I found the bug in _enginegame.js_ on ai promote as well...

That's not a bug... 'N' is standard for knight in chess, 'K' is king. Even though you obviously don't promote to a king, it would be stupid to change the entire standard just for pawn promotion.

**Comment by varunpvp** [comment]
Maybe, this will be helpful.
```
function isPromoting(fen, move) {
  const chess = new Chess(fen);

  const piece = chess.get(move.from);

  if (piece?.type !== "p") {
    return false;
  }

  if (piece.color !== chess.turn()) {
    return false;
  }

  if (!["1", "8"].some((it) => move.to.endsWith(it))) {
    return false;
  }

  return chess
    .moves({ square: move.from, verbose: true })
    .map((it) => it.to)
    .includes(move.to);
}
```
