### ISSUE TITLE
bug: pgn headers write in double due to forgotten regex~ness of string

### ISSUE THREAD

**Issue by jzacsh** [jhlywa/chess.js#51]
bug description copy/pasted from https://github.com/jzacsh/chess.js/commit/232e5d0c5249ec30414101fdefb7a7d7155c1ae1

``` javascript
var chess = new Chess();
chess.move({from: 'e2', to: 'e4'});
var pgn = chess.pgn({max_width: 5, newline_char: '\n'});
// output:
// [White "carolyn"]
// [Black "hippo"]
// [Date "2014-1-18"]
// 
// 1. e4

var chessB = new Chess();
chessB.load_pgn(pgn);

// BUG HERE:
chessB.pgn({max_width: 5, newline_char: '\n'});
// outputs: [[White "carolyn"] [Black "hippo"] [Date "2014-1-18"] "[White "carolyn"] [Black "hippo"] [Date "2014-1-18"]"]  1. e4
```

test added that confirms this behavior in: https://github.com/jzacsh/chess.js/commit/fa552174120988f12f911cfffa7b58b69d73ef31

**Comment by tjadenad** [comment]
I know this is really old, but I was perusing this code for the first time and came across the mask function:
`function mask(str) {
  return str.replace(/\\/g, '\\');
}`
Please correct me if I'm wrong, but this function does absolutely nothing and may as well just return str itself.  Is there any reason to keep this mask() function at all?
