### ISSUE TITLE
Castling in chess 960

### ISSUE THREAD

**Issue by salvador-dali** [jhlywa/chess.js#67]
I tried to use your amazing library to play chess 960. 

I am initializing it 
`var chess = new Chess('nrbqkrnb/pppppppp/8/8/8/8/PPPPPPPP/NRBQKRNB w KQkq -');` and then I can play it nicely. Till I have to castle. Is is possible to add ability to recognize castling in chess 960?

**Comment by ngocdaothanh** [comment]
Hi,
Can you merge the branch 960 to the branch master?
The difference between the two is 2 years!

**Comment by ngocdaothanh** [comment]
Hi,
Can you please merge the 960 branch to the master branch?
