### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by lukekarrys** [jhlywa/chess.js#72]
First off, let me say that this is such a great library! It's been indispensable to me in writing other JS chess code.

I'm publishing node/browser code to npm that depends on chess.js and the last published version of this library is `0.1.0` which has some differences (based on a quick diff of the code). It'd be very helpful to have the latest code on npm (and for future updates). Bonus points if it follows semver :smile: 

Thanks!

**Comment by matteocontrini** [comment]
Up.

**Comment by matteocontrini** [comment]
I think [this](https://www.npmjs.com/package/chessli.js) package on npm is updated and the link brings to this repository, although the package name is slightly different.

```
npm install chessli.js
```

**Comment by matteocontrini** [comment]
Well... not updated as I thought. The `ascii` function is not there for example

**Comment by jhlywa** [comment]
Semver has been implemented and chess.js has been updated in npm.
