### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by lightbeard** [jhlywa/chess.js#73]
Thank you from someone very grateful for this library!

We'd like to use chess.js (with <a href="http://chessboardjs.com/">chessboard.js</a>) on a competitive play site. The other js/css libraries we utilize have CDN (we use fallbacks to local downloads if they can't be reached). Has there been some thought to adding this to a CDN? I believe it's free to add javascript libraries to <a href="https://cdnjs.com">cdnjs</a>

**Comment by jbkunst** [comment]
+1

**Comment by PeterDaveHello** [comment]
Pull request merged!
Now you can access it via:
https://cdnjs.com/libraries/chess.js
https://cdnjs.cloudflare.com/ajax/libs/chess.js/0.9.3/chess.min.js

**Comment by jhlywa** [comment]
Thanks @PeterDaveHello!

**Comment by PeterDaveHello** [comment]
:facepunch:

**Comment by jaredkrinke** [comment]
The latest version on cdnjs is 0.13.4, but the latest version on npm is 1.4.0. Unless I missed something, this integration no longer works.

**Comment by neofight78** [comment]
It stopped working once we moved to a typescript project, but the package is available here: https://cdn.jsdelivr.net/npm/chess.js
