### ISSUE TITLE
Incorrect SAN generated.

### ISSUE THREAD

**Issue by tforbus** [jhlywa/chess.js#75]
![screen shot 2015-02-10 at 21 26 25](https://cloud.githubusercontent.com/assets/1789549/6142448/82557ed8-b16b-11e4-9986-0ff967dde1df.png)

In the image attached, the knight on C3 is absolutely pinned.
The next move made is Nge2, but the SAN generated is Ne2.

FEN:
```
rn2k2r/pppq1ppp/5p2/3p4/1b1P4/2NQP3/PPP2PPP/R3K1NR w KQkq - 0 1
```

**Comment by jhlywa** [comment]
The correct notation is Ne2.  Why, because there is only one legal knight move to e2, there's no need to disambiguate the move with additional algebraic descriptors.  Section 8.2.3.4 of the [PGN spec](http://www6.chessclub.com/help/PGN-spec) covers this exact position:

> Note that the above disambiguation is needed only to distinguish among moves of
> the same piece type to the same square; it is not used to distinguish among
> attacks of the same piece type to the same square.  An example of this would be
> a position with two white knights, one on square c3 and one on square g1 and a
> vacant square e2 with White to move.  Both knights attack square e2, and if
> both could legally move there, then a file disambiguation is needed; the
> (nonchecking) knight moves would be "Nce2" and "Nge2".  However, if the white
> king were at square e1 and a black bishop were at square b4 with a vacant
> square d2 (thus an absolute pin of the white knight at square c3), then only
> one white knight (the one at square g1) could move to square e2: "Ne2".
