### ISSUE TITLE
Pawn promotion without equal sign feature has been removed?

### ISSUE THREAD

**Issue by ngocdaothanh** [jhlywa/chess.js#78]
@davidmpaz
@jhlywa

There's this pull request:
https://github.com/jhlywa/chess.js/pull/33

But the latest code in master doesn't allow pawn promotion without equal sign any more. Has this feature been removed?

Now chess.js understands "fxg8=Q", but not "fxg8Q".

**Comment by ngocdaothanh** [comment]
I've sent a PR. Please review.

**Comment by jhlywa** [comment]
Can you add please add a quick test to the PR?  After all, that's how the "lazy parse" feature got dropped in the first place.

I eventually want to reevaluate how we load PGN in chess.js.  I'm of the opinion that ```load_pgn()``` should fail on non-standard SAN. Lazy parsing (or some better name) could be achieved by calling ```load_pgn({lazy: true})```

**Comment by ngocdaothanh** [comment]
Thanks.
I'll add some test.

This is not only related to PGN loading.
This is also related to the `move` method.

**Comment by ngocdaothanh** [comment]
I've added the test. Please review.

**Comment by jhlywa** [comment]
Good catch on the ```move()``` method as well.  Thanks for your contribution
