### ISSUE TITLE
es6 rewrite and support for PGN variations

### ISSUE THREAD

**Issue by aaronfi** [jhlywa/chess.js#93]
Hello.

I've been working on an extensive rewrite of chess.js for several months.  I was wondering if you or the community had any interest in my work -- or if I should just release it as a separate repo.  ("chess-es6.js"...?)

The biggest feature I added was PGN parser support for variations, as well as cursor semantics for iterating back and forth across moves.  Making a new move from anything other than the head of a variation implicitly creates a new variation.

        test("many nested variations", () => {
            const pgn = '1. d4 (1. c4 (1. b4 (1. a4 a5) 1... b5) 1... c5) (1. e4 (1. f4 (1. g4 (1. h4 h5) 1... g5) 1... f5) 1... e5) 1... d5 (1... c5 (1... b5 (1... a5))) (1... e5 (1... f5 (1... g5 2. g3) 2. f3) 2. e3) 2. e3 (2. f3 f6) (2. g3 g6) (2. h3 h6) 2... e6';
            chess.loadPgn(pgn);
            assert.equal(chess.toPgn(), pgn, "PGN parser failed to reassemble the given PGN text");
        });

Thanks.

**Comment by aaronfi** [comment]
I posted my work:  https://github.com/aaronfi/chess-es6.js

Apologies if this abuse of the issues channel.
I have not collaborated much on github before.

**Comment by davecom** [comment]
I think it's a nice refactor.  We also partially went to classes for moves, pieces, etc for the Dart port:
https://github.com/davecom/chess.dart

I'd be interested in seeing some performance comparisons.  We eventually got the Dart port to surpass chess.js when running on the Dart VM.  A lot of that was carefully choosing final variables.  I don't know if ES 6 has a similar concept of `final`.

**Comment by aaronfi** [comment]
Thanks.  I'll post some perf numbers shortly.
ES6 does have a "const".

**Comment by bokybanton** [comment]
I will fork and will try the next and prev functions and also the chess variations in the pgn game.

how about parsing big pgn files with different ways to annotate variations ?

**Comment by jhlywa** [comment]
Nice work @aaronfi.  Creating your own repo was the correct thing to do.  However, my understanding is that ES6 overall slower compared to ES5 (http://kpdecker.github.io/six-speed/).

I'll consider an ES6 refactor once performance improves.

**Comment by shaack** [comment]
Hi, I wrapped some ES6 around chess.js, combined it with my "cm-pgn" module and here I proudly present "cm-chess", which supports variations and annotations: https://github.com/shaack/cm-chess
