### ISSUE TITLE
It supports variations? ( within parenthesis in PGN)

### ISSUE THREAD

**Issue by ivanhuay** [jhlywa/chess.js#94]
I need this functionality for my pgn reader. But if it exist i can't find some documentation about this.

**Comment by bokybanton** [comment]
A fork called chess-es6.js iimplement this función

**Comment by aaronfi** [comment]
I'll post actual documentation and examples about chess-es6.js shortly.

**Comment by jhlywa** [comment]
No, chess.js doesn't yet support PGN variations. We'll gladly accept a well-documented pull request fixing this issue.
