### ISSUE TITLE
Wrong movement number after setting a position via FEN

### ISSUE THREAD

**Issue by Roofbreaker** [jhlywa/chess.js#98]
When setting a position via FEN, as in:
  var chess = new Chess();
  chess.load('4r3/8/2p2PPk/1p6/pP2p1R1/P1B5/2P2K2/3r4 w - - 1 45');

and then added some moves like for example:
  chess.move('f7')

the string returnd by method .pgn should read something like
  chess.pgn()   -> [.. FEN ...] 45. f7
instead of 
  chess.pgn()   -> [.. FEN ...] 1. f7  *** Current value returned ***
since the original FEN indicated that next move was 45 and not 1.

**Comment by jhlywa** [comment]
Fixed in master
